-- GENERATED by backend/deploy/build-migration.mjs. Do not edit this artifact.
-- InsForge wraps this ONE migration in a transaction. No top-level BEGIN/COMMIT.
-- test-platform.sql is deliberately excluded; InsForge owns platform roles and auth.users.

-- BEGIN SOURCE: backend/bootstrap/000_preflight.sql SHA256=84be34db245068ab280e2b16424656ec63e5df0c4eb2eced9ea671e3287d7d60
-- Empty-project baseline only. Execute 000..008 together in ONE transaction.
-- InsForge owns auth.users and the three roles: never create them here.
DO $bootstrap$
BEGIN
  IF current_user <> 'project_admin' THEN
    RAISE EXCEPTION 'Run bootstrap as the InsForge project_admin role';
  END IF;
  IF to_regclass('auth.users') IS NULL THEN
    RAISE EXCEPTION 'InsForge prerequisite auth.users is missing';
  END IF;
  IF NOT has_column_privilege(current_user, 'auth.users', 'id', 'SELECT')
     OR NOT has_column_privilege(current_user, 'auth.users', 'email', 'SELECT')
     OR NOT has_column_privilege(current_user, 'auth.users', 'profile', 'SELECT') THEN
    RAISE EXCEPTION 'InsForge auth.users projection privileges are missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     OR NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    RAISE EXCEPTION 'InsForge runtime roles are missing';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname LIKE 'tokentracker\_%' ESCAPE '\')
    OR EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND (p.proname LIKE 'account\_%' ESCAPE '\'
      OR p.proname LIKE 'leaderboard\_%' ESCAPE '\'
      OR p.proname LIKE 'tokentracker\_%' ESCAPE '\'
      OR p.proname = 'refresh_tokentracker_device_identity')) THEN
    RAISE EXCEPTION 'Existing TokenTracker objects found; baseline must not overwrite an existing backend';
  END IF;
END
$bootstrap$;

-- END SOURCE: backend/bootstrap/000_preflight.sql

-- BEGIN SOURCE: backend/bootstrap/001_core_tables.sql SHA256=2afa173f607f508b7dd8bf2e89b17b8ddc327df00f95178a8d4a04faedee3227
-- INFERRED_COMPATIBILITY_IMPLEMENTATION
-- Complete upstream DDL is absent. Contracts: device-token-issue.ts, ingest.ts,
-- account-devices.ts, and refresh_tokentracker_device_identity (20260719152022).
-- Defaults, ownership FKs and nonnegative checks are explicit baseline choices.
CREATE TABLE public.tokentracker_devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_name text NOT NULL,
  platform text NOT NULL,
  machine_id text,
  name_customized boolean NOT NULL DEFAULT false,
  default_device_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  UNIQUE (user_id, id)
);
CREATE UNIQUE INDEX tokentracker_devices_active_unique
  ON public.tokentracker_devices (user_id, platform, device_name) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX tokentracker_devices_active_machine_unique
  ON public.tokentracker_devices (user_id, machine_id)
  WHERE revoked_at IS NULL AND machine_id IS NOT NULL;

CREATE TABLE public.tokentracker_device_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  FOREIGN KEY (user_id, device_id) REFERENCES public.tokentracker_devices(user_id, id) ON DELETE CASCADE
);
CREATE INDEX tokentracker_device_tokens_device_idx ON public.tokentracker_device_tokens(user_id, device_id);

CREATE TABLE public.tokentracker_hourly (
  user_id uuid NOT NULL,
  device_id uuid NOT NULL,
  hour_start timestamptz NOT NULL,
  source text NOT NULL,
  model text NOT NULL,
  input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cached_input_tokens bigint NOT NULL DEFAULT 0 CHECK (cached_input_tokens >= 0),
  cache_creation_input_tokens bigint NOT NULL DEFAULT 0 CHECK (cache_creation_input_tokens >= 0),
  reasoning_output_tokens bigint NOT NULL DEFAULT 0 CHECK (reasoning_output_tokens >= 0),
  total_tokens bigint NOT NULL DEFAULT 0 CHECK (total_tokens >= 0),
  billable_total_tokens bigint NOT NULL DEFAULT 0 CHECK (billable_total_tokens >= 0),
  conversations bigint NOT NULL DEFAULT 0 CHECK (conversations >= 0),
  total_cost_usd numeric NOT NULL DEFAULT 0 CHECK (total_cost_usd >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, device_id, hour_start, source, model),
  FOREIGN KEY (user_id, device_id) REFERENCES public.tokentracker_devices(user_id, id) ON DELETE CASCADE
);
-- No total=sum check: reasoning is an informational subset for some providers.
CREATE INDEX tokentracker_hourly_user_time_idx ON public.tokentracker_hourly(user_id, hour_start);
CREATE INDEX tokentracker_hourly_time_idx ON public.tokentracker_hourly(hour_start);

-- A real sparse alias map, NOT a dummy view. Existing RPCs use device_id when
-- no alias exists. New machine_id issuance already converges on one device.
-- Upstream's historical/offline value-based clustering is unavailable and is
-- deliberately not invented. Mapping rows can be maintained by a later audited
-- repair; identity convergence deletes absorbed legacy mappings upstream.
CREATE TABLE public.tokentracker_device_machine (
  device_id uuid PRIMARY KEY REFERENCES public.tokentracker_devices(id) ON DELETE CASCADE,
  machine_cluster_id text NOT NULL
);

-- Ingest omits updated_at; dedup reads it as a tie-breaker. Preserve an explicit
-- timestamp from the upstream identity merge; stamp ordinary upserts.
CREATE FUNCTION public.tokentracker_hourly_stamp() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $fn$
BEGIN
  IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
    NEW.updated_at := clock_timestamp();
  END IF;
  RETURN NEW;
END
$fn$;
CREATE TRIGGER tokentracker_hourly_stamp BEFORE UPDATE ON public.tokentracker_hourly
FOR EACH ROW EXECUTE FUNCTION public.tokentracker_hourly_stamp();

-- END SOURCE: backend/bootstrap/001_core_tables.sql

-- BEGIN SOURCE: backend/bootstrap/002_device_identity.sql SHA256=f3b4d68a8ea377ef6376695b1be84c52e9a99ab98bdc87770168ac98d75876f2
-- Final upstream definitions only; provenance.json records exact extracted hashes.

-- UPSTREAM: migrations/20260719152022_harden-backend-concurrency.sql :: refresh_tokentracker_device_identity
CREATE OR REPLACE FUNCTION public.refresh_tokentracker_device_identity(
  p_user_id uuid,
  p_device_id uuid,
  p_device_name text,
  p_platform text
) RETURNS boolean
LANGUAGE plpgsql VOLATILE
SET search_path TO public, pg_temp
SET statement_timeout TO '15s'
AS $func$
DECLARE
  v_current_name text;
  v_name_customized boolean;
  v_current_default_name text;
  v_legacy_id uuid;
  v_legacy_name text;
  v_legacy_name_customized boolean;
  v_legacy_default_name text;
  v_target_name text;
  v_target_name_customized boolean;
  v_target_default_name text;
BEGIN
  SELECT d.device_name, d.name_customized, d.default_device_name
    INTO v_current_name, v_name_customized, v_current_default_name
  FROM public.tokentracker_devices AS d
  WHERE d.id = p_device_id
    AND d.user_id = p_user_id
    AND d.revoked_at IS NULL
    AND d.machine_id IS NOT NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  SELECT
    legacy.id,
    legacy.device_name,
    legacy.name_customized,
    legacy.default_device_name
  INTO
    v_legacy_id,
    v_legacy_name,
    v_legacy_name_customized,
    v_legacy_default_name
  FROM public.tokentracker_devices AS legacy
  WHERE legacy.user_id = p_user_id
    AND legacy.id <> p_device_id
    AND legacy.revoked_at IS NULL
    AND legacy.machine_id IS NULL
    AND legacy.platform IS NOT DISTINCT FROM p_platform
    AND (
      legacy.device_name = p_device_name
      OR legacy.default_device_name = p_device_name
    )
  ORDER BY
    CASE WHEN legacy.device_name = p_device_name THEN 0 ELSE 1 END,
    legacy.created_at,
    legacy.id
  LIMIT 1
  FOR UPDATE;

  IF v_legacy_id IS NOT NULL THEN
    INSERT INTO public.tokentracker_hourly AS canonical (
      user_id,
      device_id,
      source,
      model,
      hour_start,
      input_tokens,
      cached_input_tokens,
      cache_creation_input_tokens,
      output_tokens,
      reasoning_output_tokens,
      total_tokens,
      billable_total_tokens,
      conversations,
      created_at,
      updated_at,
      total_cost_usd
    )
    SELECT
      ranked.user_id,
      p_device_id,
      ranked.source,
      ranked.model,
      ranked.hour_start,
      ranked.input_tokens,
      ranked.cached_input_tokens,
      ranked.cache_creation_input_tokens,
      ranked.output_tokens,
      ranked.reasoning_output_tokens,
      ranked.total_tokens,
      ranked.billable_total_tokens,
      ranked.conversations,
      ranked.created_at,
      ranked.updated_at,
      ranked.total_cost_usd
    FROM (
      SELECT
        h.*,
        ROW_NUMBER() OVER (
          PARTITION BY h.user_id, h.source, h.model, h.hour_start
          ORDER BY h.total_tokens DESC, h.updated_at DESC, h.device_id = p_device_id DESC
        ) AS canonical_rank
      FROM public.tokentracker_hourly AS h
      WHERE h.user_id = p_user_id
        AND h.device_id IN (p_device_id, v_legacy_id)
    ) AS ranked
    WHERE ranked.canonical_rank = 1
    ON CONFLICT (user_id, device_id, source, model, hour_start) DO UPDATE SET
      input_tokens = EXCLUDED.input_tokens,
      cached_input_tokens = EXCLUDED.cached_input_tokens,
      cache_creation_input_tokens = EXCLUDED.cache_creation_input_tokens,
      output_tokens = EXCLUDED.output_tokens,
      reasoning_output_tokens = EXCLUDED.reasoning_output_tokens,
      total_tokens = EXCLUDED.total_tokens,
      billable_total_tokens = EXCLUDED.billable_total_tokens,
      conversations = EXCLUDED.conversations,
      created_at = EXCLUDED.created_at,
      updated_at = EXCLUDED.updated_at,
      total_cost_usd = EXCLUDED.total_cost_usd;

    DELETE FROM public.tokentracker_hourly
    WHERE user_id = p_user_id
      AND device_id = v_legacy_id;

    UPDATE public.tokentracker_device_tokens
    SET device_id = p_device_id
    WHERE user_id = p_user_id
      AND device_id = v_legacy_id;

    IF to_regclass('public.tokentracker_device_machine') IS NOT NULL THEN
      EXECUTE
        'DELETE FROM public.tokentracker_device_machine WHERE device_id = $1'
      USING v_legacy_id;
    END IF;

    UPDATE public.tokentracker_devices
    SET revoked_at = clock_timestamp()
    WHERE id = v_legacy_id
      AND user_id = p_user_id
      AND revoked_at IS NULL
      AND machine_id IS NULL;
  END IF;

  v_target_name := CASE
    WHEN v_name_customized THEN v_current_name
    WHEN COALESCE(v_legacy_name_customized, false) THEN v_legacy_name
    ELSE p_device_name
  END;
  v_target_name_customized :=
    v_name_customized OR COALESCE(v_legacy_name_customized, false);
  v_target_default_name := CASE
    WHEN v_name_customized THEN v_current_default_name
    WHEN COALESCE(v_legacy_name_customized, false)
      THEN COALESCE(v_legacy_default_name, p_device_name)
    ELSE v_current_default_name
  END;

  BEGIN
    UPDATE public.tokentracker_devices
    SET
      device_name = v_target_name,
      platform = p_platform,
      name_customized = v_target_name_customized,
      default_device_name = v_target_default_name
    WHERE id = p_device_id
      AND user_id = p_user_id
      AND revoked_at IS NULL;
  EXCEPTION WHEN unique_violation THEN
    NULL;
  END;

  RETURN true;
END;
$func$;

-- END SOURCE: backend/bootstrap/002_device_identity.sql

-- BEGIN SOURCE: backend/bootstrap/003_account_session_states.sql SHA256=91d13dd992783b778664bd22743c10e8d3e992dc6d7d58ba72a615730c6b8e98
-- Final upstream definitions only; provenance.json records exact extracted hashes.

-- UPSTREAM: migrations/20260817120000_account-session-states.sql :: tokentracker_account_session_states
CREATE TABLE IF NOT EXISTS public.tokentracker_account_session_states (
  user_id uuid NOT NULL,
  source text NOT NULL,
  -- Provider-side session identity (TRAE session_id): stable across
  -- repeated fetches and window changes (VERIFIED), account-scoped rather
  -- than device-scoped in the request (cross-device id stability itself is
  -- NOT DIRECTLY VERIFIED - see the header's evidence split).
  session_id text NOT NULL,
  model text NOT NULL,
  -- Canonical UTC half-hour bucket of this session's CURRENT placement.
  bucket_start timestamptz NOT NULL,
  input_tokens bigint NOT NULL,
  output_tokens bigint NOT NULL,
  cached_input_tokens bigint NOT NULL,
  cache_creation_input_tokens bigint NOT NULL,
  reasoning_output_tokens bigint NOT NULL,
  total_tokens bigint NOT NULL,
  -- Client logical fetch stamp (see the freshness note above). Ops metadata
  -- only - updated_at (first server write time) never participates in
  -- correctness.
  snapshot_verified_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, source, session_id),
  CHECK (
    total_tokens =
      input_tokens + cached_input_tokens + cache_creation_input_tokens + output_tokens
  ),
  CHECK (
    input_tokens >= 0 AND output_tokens >= 0 AND cached_input_tokens >= 0
    AND cache_creation_input_tokens >= 0 AND reasoning_output_tokens >= 0
    AND total_tokens >= 0
  )
);

-- UPSTREAM: migrations/20260817120000_account-session-states.sql :: tokentracker_account_session_states_bucket_idx
CREATE INDEX IF NOT EXISTS tokentracker_account_session_states_bucket_idx
  ON public.tokentracker_account_session_states (user_id, source, bucket_start);

-- UPSTREAM: migrations/20260817120000_account-session-states.sql :: tokentracker_upsert_account_session_states
CREATE OR REPLACE FUNCTION public.tokentracker_upsert_account_session_states(
  p_user_id uuid,
  p_states jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $fn$
DECLARE
  v_applied integer;
BEGIN
  INSERT INTO tokentracker_account_session_states AS t
    (user_id, source, session_id, model, bucket_start,
     input_tokens, output_tokens, cached_input_tokens,
     cache_creation_input_tokens, reasoning_output_tokens, total_tokens,
     snapshot_verified_at)
  SELECT
    p_user_id, x.source, x.session_id, x.model, x.bucket_start,
    x.input_tokens, x.output_tokens, x.cached_input_tokens,
    x.cache_creation_input_tokens, x.reasoning_output_tokens, x.total_tokens,
    x.snapshot_verified_at
  FROM jsonb_to_recordset(p_states) AS x(
    source text, session_id text, model text, bucket_start timestamptz,
    input_tokens bigint, output_tokens bigint, cached_input_tokens bigint,
    cache_creation_input_tokens bigint, reasoning_output_tokens bigint,
    total_tokens bigint, snapshot_verified_at timestamptz)
  ON CONFLICT (user_id, source, session_id) DO UPDATE SET
    model = EXCLUDED.model,
    bucket_start = EXCLUDED.bucket_start,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    cached_input_tokens = EXCLUDED.cached_input_tokens,
    cache_creation_input_tokens = EXCLUDED.cache_creation_input_tokens,
    reasoning_output_tokens = EXCLUDED.reasoning_output_tokens,
    total_tokens = EXCLUDED.total_tokens,
    snapshot_verified_at = EXCLUDED.snapshot_verified_at,
    updated_at = now()
  WHERE EXCLUDED.snapshot_verified_at > t.snapshot_verified_at;

  GET DIAGNOSTICS v_applied = ROW_COUNT;
  RETURN v_applied;
END
$fn$;

-- END SOURCE: backend/bootstrap/003_account_session_states.sql

-- BEGIN SOURCE: backend/bootstrap/004_account_usage_rpc.sql SHA256=147fb682fac26c2634f7c8d1414bb91f7346e55553570647f2e270b8d491d116
-- Final upstream definitions only; provenance.json records exact extracted hashes.

-- UPSTREAM: migrations/20260718071507_add-shared-account-usage-cache.sql :: tokentracker_account_usage_cache
CREATE UNLOGGED TABLE public.tokentracker_account_usage_cache (
  cache_key text PRIMARY KEY,
  fetched_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  result jsonb NOT NULL
);

-- UPSTREAM: migrations/20260718071507_add-shared-account-usage-cache.sql :: tokentracker_account_usage_cache_fetched_at_idx
CREATE INDEX tokentracker_account_usage_cache_fetched_at_idx
  ON public.tokentracker_account_usage_cache (fetched_at);

-- UPSTREAM: migrations/20260904083630_add-single-scan-account-usage-candidate.sql :: account_usage_grouped_single_scan_candidate (promoted as account_usage_grouped)
CREATE OR REPLACE FUNCTION public.account_usage_grouped(
  p_user_id uuid,
  p_device_ids uuid[],
  p_from timestamptz,
  p_to timestamptz,
  p_trunc text,
  p_tz text,
  p_offset_min integer
) RETURNS jsonb
LANGUAGE sql STABLE
SET search_path TO public, pg_temp
SET statement_timeout TO '8s'
AS $func$
  WITH tzr AS (
    SELECT CASE
      WHEN p_tz IS NOT NULL AND p_tz <> ''
       AND EXISTS (SELECT 1 FROM pg_timezone_names WHERE name = p_tz)
      THEN p_tz ELSE NULL
    END AS tz
  ), base AS MATERIALIZED (
    SELECT
      h.device_id, h.hour_start, h.source, h.model,
      h.total_tokens::bigint AS total_tokens,
      h.input_tokens::bigint AS input_tokens,
      h.output_tokens::bigint AS output_tokens,
      h.cached_input_tokens::bigint AS cached_input_tokens,
      h.cache_creation_input_tokens::bigint AS cache_creation_input_tokens,
      h.reasoning_output_tokens::bigint AS reasoning_output_tokens,
      h.conversations::bigint AS conversations,
      h.updated_at
    FROM public.tokentracker_hourly h
    WHERE h.user_id = p_user_id
      AND h.hour_start >= p_from AND h.hour_start < p_to
      AND (
        h.source = 'cursor'
        OR (
          h.source NOT IN ('cursor', 'trae-cn')
          AND h.device_id = ANY(p_device_ids)
        )
      )
  ), hourly AS (
    SELECT mac.hour_start, mac.source, mac.model,
      mac.total_tokens, mac.input_tokens, mac.output_tokens,
      mac.cached_input_tokens, mac.cache_creation_input_tokens,
      mac.reasoning_output_tokens, mac.conversations
    FROM (
      SELECT DISTINCT ON (
        COALESCE(dm.machine_cluster_id, h.device_id::text),
        h.hour_start, h.source, h.model
      )
        h.hour_start, h.source, h.model,
        h.total_tokens, h.input_tokens, h.output_tokens,
        h.cached_input_tokens, h.cache_creation_input_tokens,
        h.reasoning_output_tokens, h.conversations
      FROM base h
      LEFT JOIN public.tokentracker_device_machine dm ON dm.device_id = h.device_id
      WHERE h.source NOT IN ('cursor', 'trae-cn')
        AND h.device_id = ANY(p_device_ids)
      ORDER BY COALESCE(dm.machine_cluster_id, h.device_id::text),
        h.hour_start, h.source, h.model, h.total_tokens DESC, h.updated_at DESC
    ) mac

    UNION ALL

    SELECT d.hour_start, d.source, d.model,
      d.total_tokens, d.input_tokens, d.output_tokens,
      d.cached_input_tokens, d.cache_creation_input_tokens,
      d.reasoning_output_tokens, d.conversations
    FROM (
      SELECT DISTINCT ON (h.hour_start, h.source, h.model)
        h.hour_start, h.source, h.model,
        h.total_tokens, h.input_tokens, h.output_tokens,
        h.cached_input_tokens, h.cache_creation_input_tokens,
        h.reasoning_output_tokens, h.conversations
      FROM base h
      WHERE h.source = 'cursor'
      ORDER BY h.hour_start, h.source, h.model, h.total_tokens DESC, h.updated_at DESC
    ) d

    UNION ALL

    SELECT s.bucket_start, s.source, s.model,
      SUM(s.total_tokens)::bigint, SUM(s.input_tokens)::bigint,
      SUM(s.output_tokens)::bigint, SUM(s.cached_input_tokens)::bigint,
      SUM(s.cache_creation_input_tokens)::bigint,
      SUM(s.reasoning_output_tokens)::bigint, COUNT(*)::bigint
    FROM public.tokentracker_account_session_states s
    WHERE s.user_id = p_user_id
      AND s.bucket_start >= p_from AND s.bucket_start < p_to
      AND s.source = 'trae-cn'
    GROUP BY s.bucket_start, s.source, s.model
  ), located AS (
    SELECT
      CASE p_trunc
        WHEN 'hour' THEN to_char(date_trunc('hour', local_ts), 'YYYY-MM-DD"T"HH24:00:00')
        WHEN 'day' THEN to_char(date_trunc('day', local_ts), 'YYYY-MM-DD')
        WHEN 'month' THEN to_char(date_trunc('month', local_ts), 'YYYY-MM')
        ELSE ''
      END AS bucket,
      source, model,
      CASE
        WHEN lower(model) LIKE '%deepseek-v4-flash%'
          OR lower(model) LIKE '%deepseek-v4-pro%'
        THEN CASE
          WHEN (
            extract(hour FROM hour_start AT TIME ZONE 'UTC') >= 1
            AND extract(hour FROM hour_start AT TIME ZONE 'UTC') < 4
          ) OR (
            extract(hour FROM hour_start AT TIME ZONE 'UTC') >= 6
            AND extract(hour FROM hour_start AT TIME ZONE 'UTC') < 10
          ) THEN 'peak' ELSE 'off_peak'
        END
        ELSE 'peak'
      END AS pricing_tier,
      total_tokens, input_tokens, output_tokens, cached_input_tokens,
      cache_creation_input_tokens, reasoning_output_tokens, conversations
    FROM hourly CROSS JOIN tzr
    CROSS JOIN LATERAL (
      SELECT CASE
        WHEN tzr.tz IS NOT NULL THEN hour_start AT TIME ZONE tzr.tz
        WHEN p_offset_min IS NOT NULL
          THEN (hour_start AT TIME ZONE 'UTC') + make_interval(mins => p_offset_min)
        ELSE hour_start AT TIME ZONE 'UTC'
      END AS local_ts
    ) local_time
  ), grouped AS (
    SELECT bucket, source, model, pricing_tier,
      SUM(total_tokens)::bigint AS total_tokens,
      SUM(input_tokens)::bigint AS input_tokens,
      SUM(output_tokens)::bigint AS output_tokens,
      SUM(cached_input_tokens)::bigint AS cached_input_tokens,
      SUM(cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
      SUM(reasoning_output_tokens)::bigint AS reasoning_output_tokens,
      SUM(conversations)::bigint AS conversations
    FROM located
    GROUP BY bucket, source, model, pricing_tier
  )
  SELECT COALESCE(
    jsonb_agg(to_jsonb(grouped.*) ORDER BY bucket, source, model, pricing_tier),
    '[]'::jsonb
  ) FROM grouped
$func$;

-- UPSTREAM: migrations/20260904090000_promote-single-scan-account-usage.sql :: account_usage_grouped_v2
CREATE OR REPLACE FUNCTION public.account_usage_grouped_v2(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_trunc text,
  p_tz text,
  p_offset_min integer
) RETURNS jsonb
LANGUAGE sql STABLE
SET search_path TO public, pg_temp
SET statement_timeout TO '8s'
AS $func$
  WITH active AS (
    SELECT COALESCE(array_agg(d.id ORDER BY d.id), ARRAY[]::uuid[]) AS ids
    FROM public.tokentracker_devices d
    WHERE d.user_id = p_user_id AND d.revoked_at IS NULL
  ), scoped AS (
    SELECT ids,
      CASE WHEN p_device_id IS NOT NULL AND p_device_id = ANY(ids)
        THEN ARRAY[p_device_id]::uuid[] ELSE ids END AS selected_ids
    FROM active
  )
  SELECT CASE WHEN cardinality(ids) = 0 THEN '[]'::jsonb
    ELSE public.account_usage_grouped(
      p_user_id, selected_ids, p_from, p_to, p_trunc, p_tz, p_offset_min
    ) END
  FROM scoped
$func$;

-- UPSTREAM: migrations/20260821173500_deepseek-v4-time-pricing.sql :: account_usage_grouped_cached
CREATE OR REPLACE FUNCTION public.account_usage_grouped_cached(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_trunc text,
  p_tz text,
  p_offset_min integer
) RETURNS jsonb
LANGUAGE plpgsql VOLATILE
SET search_path TO public, pg_temp
SET statement_timeout TO '8s'
AS $func$
DECLARE
  v_cache_key text;
  v_result jsonb;
BEGIN
  v_cache_key := concat_ws(
    chr(31), 'v2-deepseek-time-pricing', p_user_id::text,
    COALESCE(p_device_id::text, ''),
    to_char(p_from AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US'),
    to_char(p_to AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US'),
    p_trunc, COALESCE(p_tz, ''), COALESCE(p_offset_min::text, '')
  );

  SELECT c.result INTO v_result
  FROM public.tokentracker_account_usage_cache c
  WHERE c.cache_key = v_cache_key
    AND c.fetched_at >= clock_timestamp() - interval '30 seconds';
  IF FOUND THEN RETURN v_result; END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(v_cache_key, 0));
  SELECT c.result INTO v_result
  FROM public.tokentracker_account_usage_cache c
  WHERE c.cache_key = v_cache_key
    AND c.fetched_at >= clock_timestamp() - interval '30 seconds';
  IF FOUND THEN RETURN v_result; END IF;

  v_result := public.account_usage_grouped_v2(
    p_user_id, p_device_id, p_from, p_to, p_trunc, p_tz, p_offset_min
  );

  INSERT INTO public.tokentracker_account_usage_cache AS c (cache_key, fetched_at, result)
  VALUES (v_cache_key, clock_timestamp(), v_result)
  ON CONFLICT (cache_key) DO UPDATE
  SET fetched_at = EXCLUDED.fetched_at, result = EXCLUDED.result;

  IF random() < 0.01 THEN
    WITH stale AS (
      SELECT s.cache_key
      FROM public.tokentracker_account_usage_cache s
      WHERE s.fetched_at < clock_timestamp() - interval '5 minutes'
      ORDER BY s.fetched_at, s.cache_key
      FOR UPDATE SKIP LOCKED
      LIMIT 256
    )
    DELETE FROM public.tokentracker_account_usage_cache c
    USING stale WHERE c.cache_key = stale.cache_key;
  END IF;
  RETURN v_result;
END
$func$;

-- UPSTREAM: migrations/20260918041500_fold-account-summary-and-heatmap-aggregation.sql :: account_summary_compact
CREATE OR REPLACE FUNCTION public.account_summary_compact(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_tz text,
  p_offset_min integer,
  p_range_from text,
  p_range_to text
) RETURNS jsonb
LANGUAGE sql
VOLATILE
SET search_path TO 'public', 'pg_temp'
SET statement_timeout TO '8s'
AS $fn$
  WITH raw AS (
    SELECT public.account_usage_grouped_cached(
      p_user_id, p_device_id, p_from, p_to, 'day', p_tz, p_offset_min
    ) AS j
  ), g AS (
    SELECT
      e->>'bucket' AS bucket,
      e->>'source' AS source,
      e->>'model' AS model,
      e->>'pricing_tier' AS pricing_tier,
      COALESCE((e->>'total_tokens')::bigint, 0) AS total_tokens,
      COALESCE((e->>'input_tokens')::bigint, 0) AS input_tokens,
      COALESCE((e->>'output_tokens')::bigint, 0) AS output_tokens,
      COALESCE((e->>'cached_input_tokens')::bigint, 0) AS cached_input_tokens,
      COALESCE((e->>'cache_creation_input_tokens')::bigint, 0) AS cache_creation_input_tokens,
      COALESCE((e->>'reasoning_output_tokens')::bigint, 0) AS reasoning_output_tokens,
      COALESCE((e->>'conversations')::bigint, 0) AS conversations
    FROM raw, jsonb_array_elements(raw.j) e
  ), in_range AS (
    SELECT * FROM g WHERE bucket >= p_range_from AND bucket <= p_range_to
  ), dims AS (
    SELECT source, model, pricing_tier,
      SUM(input_tokens) AS i,
      SUM(output_tokens) AS o,
      SUM(cached_input_tokens) AS cr,
      SUM(cache_creation_input_tokens) AS cw,
      SUM(reasoning_output_tokens) AS rs
    FROM in_range
    GROUP BY source, model, pricing_tier
  ), days AS (
    SELECT bucket, SUM(total_tokens) AS t, SUM(conversations) AS c
    FROM g GROUP BY bucket
  )
  SELECT jsonb_build_object(
    'cost_dims', COALESCE(
      (SELECT jsonb_agg(jsonb_build_array(source, model, pricing_tier, i, o, cr, cw, rs)
                        ORDER BY source, model, pricing_tier) FROM dims),
      '[]'::jsonb),
    'day_rollup', COALESCE(
      (SELECT jsonb_agg(jsonb_build_array(bucket, t, c) ORDER BY bucket) FROM days),
      '[]'::jsonb),
    'range_totals', (SELECT jsonb_build_object(
        'total_tokens', COALESCE(SUM(total_tokens), 0),
        'input_tokens', COALESCE(SUM(input_tokens), 0),
        'output_tokens', COALESCE(SUM(output_tokens), 0),
        'cached_input_tokens', COALESCE(SUM(cached_input_tokens), 0),
        'cache_creation_input_tokens', COALESCE(SUM(cache_creation_input_tokens), 0),
        'reasoning_output_tokens', COALESCE(SUM(reasoning_output_tokens), 0),
        'conversation_count', COALESCE(SUM(conversations), 0),
        'active_days', COUNT(DISTINCT bucket)
      ) FROM in_range)
  )
$fn$;

-- UPSTREAM: migrations/20260918041500_fold-account-summary-and-heatmap-aggregation.sql :: account_heatmap_compact
CREATE OR REPLACE FUNCTION public.account_heatmap_compact(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_tz text,
  p_offset_min integer,
  p_range_from text,
  p_range_to text
) RETURNS jsonb
LANGUAGE sql
VOLATILE
SET search_path TO 'public', 'pg_temp'
SET statement_timeout TO '8s'
AS $fn$
  WITH raw AS (
    SELECT public.account_usage_grouped_cached(
      p_user_id, p_device_id, p_from, p_to, 'day', p_tz, p_offset_min
    ) AS j
  ), g AS (
    SELECT
      e->>'bucket' AS bucket,
      COALESCE(NULLIF(e->>'model', ''), 'unknown') AS model,
      COALESCE((e->>'total_tokens')::bigint, 0) AS tt
    FROM raw, jsonb_array_elements(raw.j) e
    WHERE e->>'bucket' >= p_range_from AND e->>'bucket' <= p_range_to
  ), per_model AS (
    SELECT bucket, model, SUM(tt) AS mt
    FROM g GROUP BY bucket, model
  ), per_day AS (
    SELECT bucket, SUM(mt) AS t, jsonb_object_agg(model, mt) AS models
    FROM per_model GROUP BY bucket
  )
  SELECT COALESCE(
    (SELECT jsonb_agg(jsonb_build_array(bucket, t, models) ORDER BY bucket) FROM per_day),
    '[]'::jsonb)
$fn$;

-- UPSTREAM: migrations/20260918043000_fold-account-model-breakdown-aggregation.sql :: account_model_breakdown_compact
CREATE OR REPLACE FUNCTION public.account_model_breakdown_compact(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_tz text,
  p_offset_min integer,
  p_range_from text,
  p_range_to text
) RETURNS jsonb
LANGUAGE sql
VOLATILE
SET search_path TO 'public', 'pg_temp'
SET statement_timeout TO '8s'
AS $fn$
  WITH raw AS (
    SELECT public.account_usage_grouped_cached(
      p_user_id, p_device_id, p_from, p_to, 'day', p_tz, p_offset_min
    ) AS j
  ), g AS (
    SELECT
      e->>'bucket' AS bucket,
      e->>'source' AS source,
      e->>'model' AS model,
      e->>'pricing_tier' AS pricing_tier,
      COALESCE((e->>'total_tokens')::bigint, 0) AS total_tokens,
      COALESCE((e->>'input_tokens')::bigint, 0) AS input_tokens,
      COALESCE((e->>'output_tokens')::bigint, 0) AS output_tokens,
      COALESCE((e->>'cached_input_tokens')::bigint, 0) AS cached_input_tokens,
      COALESCE((e->>'cache_creation_input_tokens')::bigint, 0) AS cache_creation_input_tokens,
      COALESCE((e->>'reasoning_output_tokens')::bigint, 0) AS reasoning_output_tokens
    FROM raw, jsonb_array_elements(raw.j) e
  ), dims AS (
    SELECT source, model, pricing_tier,
      SUM(total_tokens) AS tt,
      SUM(input_tokens) AS i,
      SUM(output_tokens) AS o,
      SUM(cached_input_tokens) AS cr,
      SUM(cache_creation_input_tokens) AS cw,
      SUM(reasoning_output_tokens) AS rs
    FROM g
    WHERE bucket >= p_range_from AND bucket <= p_range_to
    GROUP BY source, model, pricing_tier
  )
  SELECT COALESCE(
    (SELECT jsonb_agg(jsonb_build_array(source, model, pricing_tier, tt, i, o, cr, cw, rs)
                      ORDER BY source, model, pricing_tier) FROM dims),
    '[]'::jsonb)
$fn$;

-- UPSTREAM: migrations/20260918050000_fold-account-daily-aggregation.sql :: account_daily_compact
CREATE OR REPLACE FUNCTION public.account_daily_compact(
  p_user_id uuid,
  p_device_id uuid,
  p_from timestamptz,
  p_to timestamptz,
  p_tz text,
  p_offset_min integer,
  p_range_from text,
  p_range_to text
) RETURNS jsonb
LANGUAGE sql
VOLATILE
SET search_path TO 'public', 'pg_temp'
SET statement_timeout TO '8s'
AS $fn$
  WITH raw AS (
    SELECT public.account_usage_grouped_cached(
      p_user_id, p_device_id, p_from, p_to, 'day', p_tz, p_offset_min
    ) AS j
  ), g AS (
    SELECT
      e->>'bucket' AS bucket,
      e->>'source' AS source,
      e->>'model' AS model,
      e->>'pricing_tier' AS pricing_tier,
      COALESCE(NULLIF(e->>'model', ''), 'unknown') AS model_key,
      COALESCE((e->>'total_tokens')::bigint, 0) AS total_tokens,
      COALESCE((e->>'input_tokens')::bigint, 0) AS input_tokens,
      COALESCE((e->>'output_tokens')::bigint, 0) AS output_tokens,
      COALESCE((e->>'cached_input_tokens')::bigint, 0) AS cached_input_tokens,
      COALESCE((e->>'cache_creation_input_tokens')::bigint, 0) AS cache_creation_input_tokens,
      COALESCE((e->>'reasoning_output_tokens')::bigint, 0) AS reasoning_output_tokens,
      COALESCE((e->>'conversations')::bigint, 0) AS conversations
    FROM raw, jsonb_array_elements(raw.j) e
    WHERE e->>'bucket' >= p_range_from AND e->>'bucket' <= p_range_to
  ), per_day_model AS (
    SELECT bucket, model_key, SUM(total_tokens) AS mt
    FROM g GROUP BY bucket, model_key
  ), models AS (
    SELECT bucket, jsonb_object_agg(model_key, mt) AS mm
    FROM per_day_model GROUP BY bucket
  ), days AS (
    SELECT bucket,
      SUM(total_tokens) AS tt, SUM(input_tokens) AS i, SUM(output_tokens) AS o,
      SUM(cached_input_tokens) AS cr, SUM(cache_creation_input_tokens) AS cw,
      SUM(reasoning_output_tokens) AS rs, SUM(conversations) AS cv
    FROM g GROUP BY bucket
  ), cost AS (
    SELECT bucket, source, model, pricing_tier,
      SUM(input_tokens) AS i, SUM(output_tokens) AS o,
      SUM(cached_input_tokens) AS cr, SUM(cache_creation_input_tokens) AS cw,
      SUM(reasoning_output_tokens) AS rs
    FROM g GROUP BY bucket, source, model, pricing_tier
  )
  SELECT jsonb_build_object(
    'days', COALESCE(
      (SELECT jsonb_agg(jsonb_build_array(d.bucket, d.tt, d.i, d.o, d.cr, d.cw, d.rs, d.cv, m.mm)
                        ORDER BY d.bucket)
       FROM days d JOIN models m ON m.bucket = d.bucket),
      '[]'::jsonb),
    'cost_dims', COALESCE(
      (SELECT jsonb_agg(jsonb_build_array(bucket, source, model, pricing_tier, i, o, cr, cw, rs)
                        ORDER BY bucket, source, model, pricing_tier) FROM cost),
      '[]'::jsonb)
  )
$fn$;

-- END SOURCE: backend/bootstrap/004_account_usage_rpc.sql

-- BEGIN SOURCE: backend/bootstrap/005_user_profiles.sql SHA256=130345b46d483f4e3093b6125b1f98467e1720a2e1968346533f1ba5c01b4236
-- INFERRED_COMPATIBILITY_IMPLEMENTATION
-- Writable settings and read-only view are documented in public-visibility.ts.
-- Settings default false; only trusted Edge functions may access these objects.
-- IMPORTANT: upstream public leaderboard reads do not filter is_public. A false
-- setting alone does not guarantee exclusion from the upstream public HTTP API.
CREATE TABLE public.tokentracker_user_settings (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  leaderboard_public boolean NOT NULL DEFAULT false,
  leaderboard_anonymous boolean NOT NULL DEFAULT false,
  github_url text,
  show_github_url boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE VIEW public.tokentracker_user_profiles AS
SELECT u.id AS user_id,
  COALESCE(s.display_name, u.profile->>'name', split_part(u.email, '@', 1)) AS display_name,
  u.profile->>'avatar_url' AS avatar_url
FROM auth.users u LEFT JOIN public.tokentracker_user_settings s ON s.user_id = u.id;
-- avatar_url JSON key is inferred, pending own-project OAuth metadata validation.

-- Snapshot writer contract: leaderboard-refresh.ts .upsert rows, conflict key.
CREATE TABLE public.tokentracker_leaderboard_snapshots (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period text NOT NULL CHECK (period IN ('week', 'month', 'total')),
  from_day date NOT NULL,
  to_day date NOT NULL CHECK (to_day >= from_day),
  rank bigint NOT NULL CHECK (rank > 0),
  total_tokens bigint NOT NULL DEFAULT 0,
  gpt_tokens bigint NOT NULL DEFAULT 0,
  claude_tokens bigint NOT NULL DEFAULT 0,
  gemini_tokens bigint NOT NULL DEFAULT 0,
  cursor_tokens bigint NOT NULL DEFAULT 0,
  opencode_tokens bigint NOT NULL DEFAULT 0,
  openclaw_tokens bigint NOT NULL DEFAULT 0,
  hermes_tokens bigint NOT NULL DEFAULT 0,
  kiro_tokens bigint NOT NULL DEFAULT 0,
  copilot_tokens bigint NOT NULL DEFAULT 0,
  kimi_tokens bigint NOT NULL DEFAULT 0,
  other_tokens bigint NOT NULL DEFAULT 0,
  estimated_cost_usd numeric NOT NULL DEFAULT 0,
  display_name text,
  avatar_url text,
  github_url text,
  is_public boolean NOT NULL DEFAULT false,
  generated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, period, from_day, to_day)
);
CREATE INDEX tokentracker_leaderboard_snapshots_period_rank_idx
  ON public.tokentracker_leaderboard_snapshots(period, from_day DESC, to_day DESC, rank);

-- Minimal persistent rate-limit state for refresh_try_claim; not an anti-cheat queue.
CREATE TABLE public.tokentracker_leaderboard_refresh_state (
  period text PRIMARY KEY,
  last_attempt_at timestamptz NOT NULL
);

-- END SOURCE: backend/bootstrap/005_user_profiles.sql

-- BEGIN SOURCE: backend/bootstrap/006_leaderboard_tables.sql SHA256=9c91ded8cc3411a8790bf6e77f20d61d886913101c685c04e116c1a93c4cbe0d
-- INFERRED_COMPATIBILITY_IMPLEMENTATION
-- Base shape: migrations/20260804043427_align-leaderboard-machine-clusters.sql.
-- The final reads/triggers in 20260904064000 require pricing_tier, but upstream
-- contains no matching final daily-table DDL. Tier MUST be in the primary key.
CREATE TABLE public.tokentracker_leaderboard_rollup_daily_v2 (
  user_id uuid NOT NULL,
  source text NOT NULL,
  model text NOT NULL,
  day date NOT NULL,
  pricing_tier text NOT NULL CHECK (pricing_tier IN ('peak', 'off_peak')),
  total_tokens bigint NOT NULL DEFAULT 0,
  input_tokens bigint NOT NULL DEFAULT 0,
  output_tokens bigint NOT NULL DEFAULT 0,
  cached_input_tokens bigint NOT NULL DEFAULT 0,
  cache_creation_input_tokens bigint NOT NULL DEFAULT 0,
  reasoning_output_tokens bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, source, model, day, pricing_tier)
);
CREATE INDEX tokentracker_leaderboard_rollup_daily_v2_day_idx
  ON public.tokentracker_leaderboard_rollup_daily_v2(day);

-- Exact CASE semantics from the promoted account_usage_grouped, factored into
-- the missing leaderboard helper. No price calculations or provider changes.
CREATE FUNCTION public.leaderboard_pricing_tier(model text, hour_start timestamptz)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path = pg_catalog AS $fn$
  SELECT CASE
    WHEN lower(model) LIKE '%deepseek-v4-flash%'
      OR lower(model) LIKE '%deepseek-v4-pro%'
    THEN CASE WHEN (
      extract(hour FROM hour_start AT TIME ZONE 'UTC') >= 1
      AND extract(hour FROM hour_start AT TIME ZONE 'UTC') < 4
    ) OR (
      extract(hour FROM hour_start AT TIME ZONE 'UTC') >= 6
      AND extract(hour FROM hour_start AT TIME ZONE 'UTC') < 10
    ) THEN 'peak' ELSE 'off_peak' END
    ELSE 'peak'
  END
$fn$;

-- END SOURCE: backend/bootstrap/006_leaderboard_tables.sql

-- BEGIN SOURCE: backend/bootstrap/006a_leaderboard_upstream.sql SHA256=25f134a3d3b6506fe426f5c96b4adc89f73cf5f9ecd2312ec20a9ba34b3122a0
-- Final upstream definitions only; provenance.json records exact extracted hashes.

-- UPSTREAM: migrations/20260804043427_align-leaderboard-machine-clusters.sql :: tokentracker_leaderboard_rollup_meta_v2
CREATE TABLE IF NOT EXISTS public.tokentracker_leaderboard_rollup_meta_v2 (
  id int PRIMARY KEY CHECK (id = 1),
  through timestamptz NOT NULL,
  repair_from date NOT NULL,
  rebuilt_at timestamptz NOT NULL DEFAULT now()
);

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: tokentracker_leaderboard_rollup_total_v2
CREATE TABLE IF NOT EXISTS public.tokentracker_leaderboard_rollup_total_v2 (
  user_id uuid NOT NULL,
  source text NOT NULL,
  model text NOT NULL,
  pricing_tier text NOT NULL,
  total_tokens bigint NOT NULL DEFAULT 0,
  input_tokens bigint NOT NULL DEFAULT 0,
  output_tokens bigint NOT NULL DEFAULT 0,
  cached_input_tokens bigint NOT NULL DEFAULT 0,
  cache_creation_input_tokens bigint NOT NULL DEFAULT 0,
  reasoning_output_tokens bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, source, model, pricing_tier)
);

-- UPSTREAM: migrations/20260817120000_account-session-states.sql :: leaderboard_hourly_dedup_v2
CREATE OR REPLACE FUNCTION public.leaderboard_hourly_dedup_v2(
  p_from timestamptz,
  p_to timestamptz
) RETURNS TABLE (
  user_id uuid,
  source text,
  model text,
  hour_start timestamptz,
  total_tokens bigint,
  input_tokens bigint,
  output_tokens bigint,
  cached_input_tokens bigint,
  cache_creation_input_tokens bigint,
  reasoning_output_tokens bigint
)
LANGUAGE sql STABLE
AS $func$
  WITH cfg AS (
    SELECT ARRAY['cursor', 'trae-cn']::text[] AS account_sources
  )
  -- Deduplicate device-id drift/replays inside one physical machine cluster,
  -- then add genuinely distinct machines for the same user/hour/model.
  SELECT mac.user_id, mac.source, mac.model, mac.hour_start,
    SUM(mac.total_tokens)::bigint                AS total_tokens,
    SUM(mac.input_tokens)::bigint                AS input_tokens,
    SUM(mac.output_tokens)::bigint               AS output_tokens,
    SUM(mac.cached_input_tokens)::bigint         AS cached_input_tokens,
    SUM(mac.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
    SUM(mac.reasoning_output_tokens)::bigint     AS reasoning_output_tokens
  FROM (
    SELECT DISTINCT ON (
      h.user_id,
      COALESCE(dm.machine_cluster_id, h.device_id::text),
      h.source,
      h.model,
      h.hour_start
    )
      h.user_id,
      COALESCE(dm.machine_cluster_id, h.device_id::text) AS machine_cluster_id,
      h.source, h.model, h.hour_start,
      h.total_tokens::bigint                AS total_tokens,
      h.input_tokens::bigint                AS input_tokens,
      h.output_tokens::bigint               AS output_tokens,
      h.cached_input_tokens::bigint         AS cached_input_tokens,
      h.cache_creation_input_tokens::bigint AS cache_creation_input_tokens,
      h.reasoning_output_tokens::bigint     AS reasoning_output_tokens
    FROM tokentracker_hourly h
    CROSS JOIN cfg
    JOIN tokentracker_devices d
      ON d.id = h.device_id AND d.revoked_at IS NULL
    LEFT JOIN tokentracker_device_machine dm
      ON dm.device_id = h.device_id
    WHERE h.hour_start >= p_from AND h.hour_start < p_to
      AND NOT (h.source = ANY(cfg.account_sources))
    ORDER BY
      h.user_id,
      COALESCE(dm.machine_cluster_id, h.device_id::text),
      h.source,
      h.model,
      h.hour_start,
      h.total_tokens DESC,
      h.updated_at DESC
  ) mac
  GROUP BY mac.user_id, mac.source, mac.model, mac.hour_start

  UNION ALL

  -- 'cursor' (account-level but with NO stable session identity): rows are
  -- identical across devices, so the legacy whole-row MAX pick per
  -- (user, hour, source, model) dedups them.
  SELECT acct.user_id, acct.source, acct.model, acct.hour_start,
    acct.total_tokens, acct.input_tokens, acct.output_tokens,
    acct.cached_input_tokens, acct.cache_creation_input_tokens,
    acct.reasoning_output_tokens
  FROM (
    SELECT DISTINCT ON (h.user_id, h.source, h.model, h.hour_start)
      h.user_id, h.source, h.model, h.hour_start,
      h.total_tokens::bigint                AS total_tokens,
      h.input_tokens::bigint                AS input_tokens,
      h.output_tokens::bigint               AS output_tokens,
      h.cached_input_tokens::bigint         AS cached_input_tokens,
      h.cache_creation_input_tokens::bigint AS cache_creation_input_tokens,
      h.reasoning_output_tokens::bigint     AS reasoning_output_tokens
    FROM tokentracker_hourly h
    WHERE h.hour_start >= p_from AND h.hour_start < p_to
      AND h.source = 'cursor'
    ORDER BY h.user_id, h.source, h.model, h.hour_start, h.total_tokens DESC, h.updated_at DESC
  ) acct

  UNION ALL

  -- trae-cn: canonical account truth aggregated from session states. Every
  -- device's observations of the same session collapsed to ONE row by the
  -- LWW upsert; corrections (downward / model / bucket) are already
  -- reflected because each session exists exactly once.
  SELECT s.user_id, s.source, s.model, s.bucket_start AS hour_start,
    SUM(s.total_tokens)::bigint                AS total_tokens,
    SUM(s.input_tokens)::bigint                AS input_tokens,
    SUM(s.output_tokens)::bigint               AS output_tokens,
    SUM(s.cached_input_tokens)::bigint         AS cached_input_tokens,
    SUM(s.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
    SUM(s.reasoning_output_tokens)::bigint     AS reasoning_output_tokens
  FROM tokentracker_account_session_states s
  WHERE s.bucket_start >= p_from AND s.bucket_start < p_to
    AND s.source = 'trae-cn'
  GROUP BY s.user_id, s.source, s.model, s.bucket_start
$func$;

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: leaderboard_rollup_total_v2_after_insert
CREATE OR REPLACE FUNCTION public.leaderboard_rollup_total_v2_after_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO public, pg_temp
AS $func$
BEGIN
  INSERT INTO public.tokentracker_leaderboard_rollup_total_v2 AS total (
    user_id, source, model, pricing_tier,
    total_tokens, input_tokens, output_tokens,
    cached_input_tokens, cache_creation_input_tokens, reasoning_output_tokens
  )
  SELECT
    user_id, source, model, pricing_tier,
    SUM(total_tokens)::bigint,
    SUM(input_tokens)::bigint,
    SUM(output_tokens)::bigint,
    SUM(cached_input_tokens)::bigint,
    SUM(cache_creation_input_tokens)::bigint,
    SUM(reasoning_output_tokens)::bigint
  FROM new_rows
  GROUP BY user_id, source, model, pricing_tier
  ON CONFLICT (user_id, source, model, pricing_tier) DO UPDATE SET
    total_tokens = total.total_tokens + EXCLUDED.total_tokens,
    input_tokens = total.input_tokens + EXCLUDED.input_tokens,
    output_tokens = total.output_tokens + EXCLUDED.output_tokens,
    cached_input_tokens = total.cached_input_tokens + EXCLUDED.cached_input_tokens,
    cache_creation_input_tokens = total.cache_creation_input_tokens
      + EXCLUDED.cache_creation_input_tokens,
    reasoning_output_tokens = total.reasoning_output_tokens
      + EXCLUDED.reasoning_output_tokens;
  RETURN NULL;
END
$func$;

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: leaderboard_rollup_total_v2_after_delete
CREATE OR REPLACE FUNCTION public.leaderboard_rollup_total_v2_after_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO public, pg_temp
AS $func$
BEGIN
  UPDATE public.tokentracker_leaderboard_rollup_total_v2 AS total
  SET
    total_tokens = total.total_tokens - removed.total_tokens,
    input_tokens = total.input_tokens - removed.input_tokens,
    output_tokens = total.output_tokens - removed.output_tokens,
    cached_input_tokens = total.cached_input_tokens - removed.cached_input_tokens,
    cache_creation_input_tokens = total.cache_creation_input_tokens
      - removed.cache_creation_input_tokens,
    reasoning_output_tokens = total.reasoning_output_tokens
      - removed.reasoning_output_tokens
  FROM (
    SELECT
      user_id, source, model, pricing_tier,
      SUM(total_tokens)::bigint AS total_tokens,
      SUM(input_tokens)::bigint AS input_tokens,
      SUM(output_tokens)::bigint AS output_tokens,
      SUM(cached_input_tokens)::bigint AS cached_input_tokens,
      SUM(cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
      SUM(reasoning_output_tokens)::bigint AS reasoning_output_tokens
    FROM old_rows
    GROUP BY user_id, source, model, pricing_tier
  ) AS removed
  WHERE total.user_id = removed.user_id
    AND total.source = removed.source
    AND total.model = removed.model
    AND total.pricing_tier = removed.pricing_tier;

  DELETE FROM public.tokentracker_leaderboard_rollup_total_v2
  WHERE total_tokens = 0
    AND input_tokens = 0
    AND output_tokens = 0
    AND cached_input_tokens = 0
    AND cache_creation_input_tokens = 0
    AND reasoning_output_tokens = 0;
  RETURN NULL;
END
$func$;

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: leaderboard_rollup_total_v2_after_update
CREATE OR REPLACE FUNCTION public.leaderboard_rollup_total_v2_after_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO public, pg_temp
AS $func$
BEGIN
  UPDATE public.tokentracker_leaderboard_rollup_total_v2 AS total
  SET
    total_tokens = total.total_tokens - removed.total_tokens,
    input_tokens = total.input_tokens - removed.input_tokens,
    output_tokens = total.output_tokens - removed.output_tokens,
    cached_input_tokens = total.cached_input_tokens - removed.cached_input_tokens,
    cache_creation_input_tokens = total.cache_creation_input_tokens
      - removed.cache_creation_input_tokens,
    reasoning_output_tokens = total.reasoning_output_tokens
      - removed.reasoning_output_tokens
  FROM (
    SELECT
      user_id, source, model, pricing_tier,
      SUM(total_tokens)::bigint AS total_tokens,
      SUM(input_tokens)::bigint AS input_tokens,
      SUM(output_tokens)::bigint AS output_tokens,
      SUM(cached_input_tokens)::bigint AS cached_input_tokens,
      SUM(cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
      SUM(reasoning_output_tokens)::bigint AS reasoning_output_tokens
    FROM old_rows
    GROUP BY user_id, source, model, pricing_tier
  ) AS removed
  WHERE total.user_id = removed.user_id
    AND total.source = removed.source
    AND total.model = removed.model
    AND total.pricing_tier = removed.pricing_tier;

  INSERT INTO public.tokentracker_leaderboard_rollup_total_v2 AS total (
    user_id, source, model, pricing_tier,
    total_tokens, input_tokens, output_tokens,
    cached_input_tokens, cache_creation_input_tokens, reasoning_output_tokens
  )
  SELECT
    user_id, source, model, pricing_tier,
    SUM(total_tokens)::bigint,
    SUM(input_tokens)::bigint,
    SUM(output_tokens)::bigint,
    SUM(cached_input_tokens)::bigint,
    SUM(cache_creation_input_tokens)::bigint,
    SUM(reasoning_output_tokens)::bigint
  FROM new_rows
  GROUP BY user_id, source, model, pricing_tier
  ON CONFLICT (user_id, source, model, pricing_tier) DO UPDATE SET
    total_tokens = total.total_tokens + EXCLUDED.total_tokens,
    input_tokens = total.input_tokens + EXCLUDED.input_tokens,
    output_tokens = total.output_tokens + EXCLUDED.output_tokens,
    cached_input_tokens = total.cached_input_tokens + EXCLUDED.cached_input_tokens,
    cache_creation_input_tokens = total.cache_creation_input_tokens
      + EXCLUDED.cache_creation_input_tokens,
    reasoning_output_tokens = total.reasoning_output_tokens
      + EXCLUDED.reasoning_output_tokens;

  DELETE FROM public.tokentracker_leaderboard_rollup_total_v2
  WHERE total_tokens = 0
    AND input_tokens = 0
    AND output_tokens = 0
    AND cached_input_tokens = 0
    AND cache_creation_input_tokens = 0
    AND reasoning_output_tokens = 0;
  RETURN NULL;
END
$func$;

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: tokentracker_leaderboard_rollup_daily_v2_total_insert
CREATE TRIGGER tokentracker_leaderboard_rollup_daily_v2_total_insert
AFTER INSERT ON public.tokentracker_leaderboard_rollup_daily_v2
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT
EXECUTE FUNCTION public.leaderboard_rollup_total_v2_after_insert();

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: tokentracker_leaderboard_rollup_daily_v2_total_delete
CREATE TRIGGER tokentracker_leaderboard_rollup_daily_v2_total_delete
AFTER DELETE ON public.tokentracker_leaderboard_rollup_daily_v2
REFERENCING OLD TABLE AS old_rows
FOR EACH STATEMENT
EXECUTE FUNCTION public.leaderboard_rollup_total_v2_after_delete();

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: tokentracker_leaderboard_rollup_daily_v2_total_update
CREATE TRIGGER tokentracker_leaderboard_rollup_daily_v2_total_update
AFTER UPDATE ON public.tokentracker_leaderboard_rollup_daily_v2
REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows
FOR EACH STATEMENT
EXECUTE FUNCTION public.leaderboard_rollup_total_v2_after_update();

-- END SOURCE: backend/bootstrap/006a_leaderboard_upstream.sql

-- BEGIN SOURCE: backend/bootstrap/006b_leaderboard_daily_replace.sql SHA256=4f675bcad794ab22d985c75aa04eee2dd1a0580d576ef2fc38091e91300ba7e8
-- INFERRED_COMPATIBILITY_IMPLEMENTATION
-- Based on upstream 20260804043427 replace_v2. Final reader and total triggers
-- require tier-preserving daily writes; their matching upstream writer is absent.
CREATE FUNCTION public.leaderboard_rollup_daily_replace_v2(p_from timestamptz, p_to timestamptz)
RETURNS void LANGUAGE plpgsql SET search_path = public, pg_temp AS $fn$
DECLARE v_day timestamptz := p_from;
BEGIN
  IF p_from IS NULL OR p_to IS NULL OR p_from > p_to THEN
    RAISE EXCEPTION 'Expected an ordered UTC day range';
  END IF;
  -- Upstream advance passes an empty range on a brand-new database.
  IF p_from = p_to THEN RETURN; END IF;
  IF p_from <> date_trunc('day', p_from AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
    OR p_to <> date_trunc('day', p_to AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' THEN
    RAISE EXCEPTION 'Daily rollup boundaries must be UTC midnight';
  END IF;
  -- Serialize writers so a repair's DELETE/INSERT cannot double-count totals.
  LOCK TABLE public.tokentracker_leaderboard_rollup_daily_v2 IN SHARE ROW EXCLUSIVE MODE;
  -- Preserve the upstream one-day-at-a-time scan to bound memory on catch-up.
  WHILE v_day < p_to LOOP
  DELETE FROM public.tokentracker_leaderboard_rollup_daily_v2
  WHERE day = (v_day AT TIME ZONE 'UTC')::date;
  INSERT INTO public.tokentracker_leaderboard_rollup_daily_v2
    (user_id, source, model, day, pricing_tier, total_tokens, input_tokens,
     output_tokens, cached_input_tokens, cache_creation_input_tokens, reasoning_output_tokens)
  SELECT user_id, source, model, (hour_start AT TIME ZONE 'UTC')::date,
    public.leaderboard_pricing_tier(model, hour_start), SUM(total_tokens)::bigint,
    SUM(input_tokens)::bigint, SUM(output_tokens)::bigint,
    SUM(cached_input_tokens)::bigint, SUM(cache_creation_input_tokens)::bigint,
    SUM(reasoning_output_tokens)::bigint
  FROM public.leaderboard_hourly_dedup_v2(v_day, v_day + interval '1 day')
  GROUP BY user_id, source, model, (hour_start AT TIME ZONE 'UTC')::date,
    public.leaderboard_pricing_tier(model, hour_start);
  v_day := v_day + interval '1 day';
  END LOOP;
END
$fn$;

-- END SOURCE: backend/bootstrap/006b_leaderboard_daily_replace.sql

-- BEGIN SOURCE: backend/bootstrap/007a_leaderboard_rpc.sql SHA256=b9c1bf0cd0a1409cb0ca0b5ec20c37b5c21b1cf5c1308625aaf09ae6bdb98ddf
-- Final upstream definitions only; provenance.json records exact extracted hashes.

-- UPSTREAM: migrations/20260817120000_account-session-states.sql :: leaderboard_rollup_daily_advance_v2
CREATE OR REPLACE FUNCTION public.leaderboard_rollup_daily_advance_v2()
RETURNS void
LANGUAGE plpgsql
SET work_mem TO '16MB'
SET hash_mem_multiplier TO '2'
SET statement_timeout TO '25s'
AS $func$
DECLARE
  v_from timestamptz;
  v_target timestamptz := date_trunc('day', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
  v_until timestamptz;
  v_min_day date;
  v_repair_from date;
  v_seed_gap_day date;
BEGIN
  SELECT
    (date_trunc('day', MIN(h.hour_start) AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')::date
  INTO v_min_day
  FROM public.tokentracker_hourly h;
  v_min_day := COALESCE(v_min_day, (v_target AT TIME ZONE 'UTC')::date);

  SELECT m.through, m.repair_from INTO v_from, v_repair_from
  FROM public.tokentracker_leaderboard_rollup_meta_v2 m
  WHERE m.id = 1
  FOR UPDATE;

  IF v_from IS NULL THEN
    v_from := v_min_day::timestamp AT TIME ZONE 'UTC';
    v_repair_from := v_min_day;
    INSERT INTO public.tokentracker_leaderboard_rollup_meta_v2 (
      id, through, repair_from, rebuilt_at
    ) VALUES (1, v_from, v_repair_from, now());
  END IF;

  IF v_from < v_target THEN
    -- Bootstrap/catch-up: advance at most seven closed days per request.
    v_until := LEAST(v_target, v_from + interval '7 days');
    PERFORM public.leaderboard_rollup_daily_replace_v2(v_from, v_until);
    UPDATE public.tokentracker_leaderboard_rollup_meta_v2
    SET through = v_until,
        rebuilt_at = now()
    WHERE id = 1;
    RETURN;
  END IF;

  -- Once caught up, continuously repair seven historical days per scheduled
  -- total refresh. Late history uploads, device revocations, and cluster-map
  -- changes therefore self-heal without another whole-history memory spike.
  IF v_repair_from >= (v_target AT TIME ZONE 'UTC')::date THEN
    v_repair_from := v_min_day;
  END IF;

  -- First-seed / uncovered-day prioritization (trae-cn): jump the repair
  -- window to the earliest CLOSED day that has trae-cn session states but
  -- no trae-cn rollup row yet (see the function header comment). Coverage
  -- is PER USER (the rollup PK starts at user_id): another user's same-day
  -- row does NOT cover this user's seed. A day whose rollup row exists for
  -- that user (even with stale values) is NOT a gap - corrections keep the
  -- ordinary cyclic schedule.
  SELECT MIN((s.bucket_start AT TIME ZONE 'UTC')::date) INTO v_seed_gap_day
  FROM public.tokentracker_account_session_states s
  WHERE s.source = 'trae-cn'
    AND (s.bucket_start AT TIME ZONE 'UTC')::date < (v_target AT TIME ZONE 'UTC')::date
    AND NOT EXISTS (
      SELECT 1 FROM public.tokentracker_leaderboard_rollup_daily_v2 r
      WHERE r.user_id = s.user_id
        AND r.source = 'trae-cn'
        AND r.day = (s.bucket_start AT TIME ZONE 'UTC')::date
    );
  IF v_seed_gap_day IS NOT NULL THEN
    v_repair_from := v_seed_gap_day;
  END IF;

  v_until := LEAST(
    v_target,
    (v_repair_from::timestamp AT TIME ZONE 'UTC') + interval '7 days'
  );
  PERFORM public.leaderboard_rollup_daily_replace_v2(
    v_repair_from::timestamp AT TIME ZONE 'UTC',
    v_until
  );
  UPDATE public.tokentracker_leaderboard_rollup_meta_v2
  SET repair_from = CASE
        WHEN v_until >= v_target THEN v_min_day
        ELSE (v_until AT TIME ZONE 'UTC')::date
      END,
      rebuilt_at = now()
  WHERE id = 1;
END
$func$;

-- UPSTREAM: migrations/20260904064000_cache-leaderboard-total-rollup.sql :: leaderboard_usage_grouped
CREATE OR REPLACE FUNCTION public.leaderboard_usage_grouped(
  p_from timestamptz,
  p_to timestamptz
) RETURNS jsonb
LANGUAGE plpgsql STABLE
SET search_path TO public, pg_temp
SET work_mem TO '96MB'
SET hash_mem_multiplier TO '4'
SET statement_timeout TO '25s'
AS $func$
DECLARE
  v_through timestamptz;
  v_cut timestamptz;
  v_base jsonb;
BEGIN
  SELECT m.through INTO v_through
  FROM public.tokentracker_leaderboard_rollup_meta_v2 m
  WHERE m.id = 1;
  v_cut := date_trunc(
    'day',
    LEAST(v_through, p_to) AT TIME ZONE 'UTC'
  ) AT TIME ZONE 'UTC';

  IF v_through IS NOT NULL
     AND p_from = date_trunc('day', p_from AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
     AND v_cut > p_from THEN
    IF p_from = TIMESTAMPTZ '1970-01-01 00:00:00+00'
       AND p_to >= v_through THEN
      -- The all-time period is the only caller allowed to use the aggregate
      -- without a day predicate. It still merges the open live tail so today
      -- remains current before the next closed-day rollup advance.
      SELECT COALESCE(jsonb_agg(to_jsonb(per_usm.*)), '[]'::jsonb)
      INTO v_base
      FROM (
        SELECT
          u.user_id, u.source, u.model, u.pricing_tier,
          SUM(u.total_tokens)::bigint AS total_tokens,
          SUM(u.input_tokens)::bigint AS input_tokens,
          SUM(u.output_tokens)::bigint AS output_tokens,
          SUM(u.cached_input_tokens)::bigint AS cached_input_tokens,
          SUM(u.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
          SUM(u.reasoning_output_tokens)::bigint AS reasoning_output_tokens
        FROM (
          SELECT
            r.user_id, r.source, r.model, r.pricing_tier,
            r.total_tokens, r.input_tokens, r.output_tokens,
            r.cached_input_tokens, r.cache_creation_input_tokens,
            r.reasoning_output_tokens
          FROM public.tokentracker_leaderboard_rollup_total_v2 r
          UNION ALL
          SELECT
            t.user_id, t.source, t.model,
            public.leaderboard_pricing_tier(t.model, t.hour_start) AS pricing_tier,
            t.total_tokens, t.input_tokens, t.output_tokens,
            t.cached_input_tokens, t.cache_creation_input_tokens,
            t.reasoning_output_tokens
          FROM public.leaderboard_hourly_dedup_v2(v_cut, p_to) t
        ) u
        GROUP BY u.user_id, u.source, u.model, u.pricing_tier
      ) per_usm;
    ELSE
      SELECT COALESCE(jsonb_agg(to_jsonb(per_usm.*)), '[]'::jsonb)
      INTO v_base
      FROM (
        SELECT
          u.user_id, u.source, u.model, u.pricing_tier,
          SUM(u.total_tokens)::bigint AS total_tokens,
          SUM(u.input_tokens)::bigint AS input_tokens,
          SUM(u.output_tokens)::bigint AS output_tokens,
          SUM(u.cached_input_tokens)::bigint AS cached_input_tokens,
          SUM(u.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
          SUM(u.reasoning_output_tokens)::bigint AS reasoning_output_tokens
        FROM (
          SELECT
            r.user_id, r.source, r.model, r.pricing_tier,
            r.total_tokens, r.input_tokens, r.output_tokens,
            r.cached_input_tokens, r.cache_creation_input_tokens,
            r.reasoning_output_tokens
          FROM public.tokentracker_leaderboard_rollup_daily_v2 r
          WHERE r.day >= (p_from AT TIME ZONE 'UTC')::date
            AND r.day < (v_cut AT TIME ZONE 'UTC')::date
          UNION ALL
          SELECT
            t.user_id, t.source, t.model,
            public.leaderboard_pricing_tier(t.model, t.hour_start) AS pricing_tier,
            t.total_tokens, t.input_tokens, t.output_tokens,
            t.cached_input_tokens, t.cache_creation_input_tokens,
            t.reasoning_output_tokens
          FROM public.leaderboard_hourly_dedup_v2(v_cut, p_to) t
        ) u
        GROUP BY u.user_id, u.source, u.model, u.pricing_tier
      ) per_usm;
    END IF;
  ELSE
    SELECT COALESCE(jsonb_agg(to_jsonb(per_usm.*)), '[]'::jsonb)
    INTO v_base
    FROM (
      SELECT
        d.user_id, d.source, d.model,
        public.leaderboard_pricing_tier(d.model, d.hour_start) AS pricing_tier,
        SUM(d.total_tokens)::bigint AS total_tokens,
        SUM(d.input_tokens)::bigint AS input_tokens,
        SUM(d.output_tokens)::bigint AS output_tokens,
        SUM(d.cached_input_tokens)::bigint AS cached_input_tokens,
        SUM(d.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
        SUM(d.reasoning_output_tokens)::bigint AS reasoning_output_tokens
      FROM public.leaderboard_hourly_dedup_v2(p_from, p_to) d
      GROUP BY
        d.user_id, d.source, d.model,
        public.leaderboard_pricing_tier(d.model, d.hour_start)
    ) per_usm;
  END IF;

  RETURN COALESCE(v_base, '[]'::jsonb);
END
$func$;

-- UPSTREAM: migrations/20260904064500_shard-leaderboard-total-read.sql :: leaderboard_usage_grouped_total_shard
CREATE OR REPLACE FUNCTION public.leaderboard_usage_grouped_total_shard(
  p_to timestamptz,
  p_user_from uuid,
  p_user_to uuid
) RETURNS jsonb
LANGUAGE plpgsql STABLE
SET search_path TO public, pg_temp
SET work_mem TO '48MB'
SET hash_mem_multiplier TO '2'
SET statement_timeout TO '8s'
AS $func$
DECLARE
  v_through timestamptz;
  v_cut timestamptz;
  v_result jsonb;
BEGIN
  SELECT m.through INTO v_through
  FROM public.tokentracker_leaderboard_rollup_meta_v2 m
  WHERE m.id = 1;

  IF v_through IS NULL THEN
    RAISE EXCEPTION 'leaderboard v2 rollup is not initialized';
  END IF;

  v_cut := date_trunc(
    'day',
    LEAST(v_through, p_to) AT TIME ZONE 'UTC'
  ) AT TIME ZONE 'UTC';

  SELECT COALESCE(jsonb_agg(to_jsonb(per_usm.*)), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      u.user_id, u.source, u.model, u.pricing_tier,
      SUM(u.total_tokens)::bigint AS total_tokens,
      SUM(u.input_tokens)::bigint AS input_tokens,
      SUM(u.output_tokens)::bigint AS output_tokens,
      SUM(u.cached_input_tokens)::bigint AS cached_input_tokens,
      SUM(u.cache_creation_input_tokens)::bigint AS cache_creation_input_tokens,
      SUM(u.reasoning_output_tokens)::bigint AS reasoning_output_tokens
    FROM (
      SELECT
        r.user_id, r.source, r.model, r.pricing_tier,
        r.total_tokens, r.input_tokens, r.output_tokens,
        r.cached_input_tokens, r.cache_creation_input_tokens,
        r.reasoning_output_tokens
      FROM public.tokentracker_leaderboard_rollup_total_v2 r
      WHERE (p_user_from IS NULL OR r.user_id >= p_user_from)
        AND (p_user_to IS NULL OR r.user_id < p_user_to)

      UNION ALL

      SELECT
        t.user_id, t.source, t.model,
        public.leaderboard_pricing_tier(t.model, t.hour_start) AS pricing_tier,
        t.total_tokens, t.input_tokens, t.output_tokens,
        t.cached_input_tokens, t.cache_creation_input_tokens,
        t.reasoning_output_tokens
      FROM public.leaderboard_hourly_dedup_v2(v_cut, p_to) t
      WHERE (p_user_from IS NULL OR t.user_id >= p_user_from)
        AND (p_user_to IS NULL OR t.user_id < p_user_to)
    ) u
    GROUP BY u.user_id, u.source, u.model, u.pricing_tier
  ) per_usm;

  RETURN COALESCE(v_result, '[]'::jsonb);
END
$func$;

-- UPSTREAM: migrations/20260717013000_harden-backend-hot-paths.sql :: leaderboard_user_metadata
CREATE OR REPLACE FUNCTION public.leaderboard_user_metadata(
  p_user_ids uuid[]
) RETURNS jsonb
LANGUAGE sql STABLE
SET search_path TO public, pg_temp
SET statement_timeout TO '5s'
AS $func$
  WITH requested AS (
    SELECT DISTINCT user_id
    FROM unnest(COALESCE(p_user_ids, ARRAY[]::uuid[])) AS ids(user_id)
  )
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'user_id', r.user_id,
        'leaderboard_public', COALESCE(s.leaderboard_public, false),
        'leaderboard_anonymous', COALESCE(s.leaderboard_anonymous, false),
        'github_url', s.github_url,
        'show_github_url', COALESCE(s.show_github_url, false),
        'display_name', CASE
          WHEN p.user_id IS NOT NULL THEN p.display_name
          ELSE previous.display_name
        END,
        'avatar_url', CASE
          WHEN p.user_id IS NOT NULL THEN p.avatar_url
          ELSE previous.avatar_url
        END
      )
      ORDER BY r.user_id
    ),
    '[]'::jsonb
  )
  FROM requested r
  LEFT JOIN public.tokentracker_user_settings s ON s.user_id = r.user_id
  LEFT JOIN public.tokentracker_user_profiles p ON p.user_id = r.user_id
  LEFT JOIN LATERAL (
    SELECT snap.display_name, snap.avatar_url
    FROM public.tokentracker_leaderboard_snapshots snap
    WHERE snap.user_id = r.user_id
    ORDER BY snap.generated_at DESC
    LIMIT 1
  ) previous ON p.user_id IS NULL;
$func$;

-- END SOURCE: backend/bootstrap/007a_leaderboard_rpc.sql

-- BEGIN SOURCE: backend/bootstrap/007b_refresh_claim.sql SHA256=5e0cdf45fcebac53767478cecf7c747077fe44659ccabf0c004927762e1e5163
-- INFERRED_COMPATIBILITY_IMPLEMENTATION
-- leaderboard-refresh.ts requires a boolean, atomic time-window claim. This
-- is throttling, NOT a job lease. Force (interval=0) intentionally bypasses it,
-- matching the Edge caller. A crashed attempt becomes eligible after interval.
CREATE FUNCTION public.leaderboard_refresh_try_claim(p_period text, p_min_interval_s integer)
RETURNS boolean LANGUAGE plpgsql SET search_path = public, pg_temp AS $fn$
DECLARE v_claimed text;
BEGIN
  IF p_period IS NULL OR p_period NOT IN ('week', 'month', 'total')
    OR p_min_interval_s IS NULL OR p_min_interval_s < 0 THEN
    RAISE EXCEPTION 'Invalid refresh claim arguments';
  END IF;
  INSERT INTO public.tokentracker_leaderboard_refresh_state AS s(period, last_attempt_at)
  VALUES (p_period, clock_timestamp())
  ON CONFLICT (period) DO UPDATE SET last_attempt_at = EXCLUDED.last_attempt_at
  WHERE s.last_attempt_at <= EXCLUDED.last_attempt_at - make_interval(secs => p_min_interval_s)
  RETURNING period INTO v_claimed;
  RETURN v_claimed IS NOT NULL;
END
$fn$;

-- END SOURCE: backend/bootstrap/007b_refresh_claim.sql

-- BEGIN SOURCE: backend/bootstrap/008_permissions.sql SHA256=88875c4d56eab972da19a85793015387600793bfebc27903d11d5e80ba8534db
-- INFERRED_COMPATIBILITY_IMPLEMENTATION: baseline security envelope.
-- All listed Edges authenticate their caller and query with service credentials.
-- No direct browser/client access, including public leaderboard tables/views.
-- Preflight proves these namespaces contain no preexisting TokenTracker objects.
DO $permissions$
DECLARE obj record;
BEGIN
  FOR obj IN SELECT c.relname, c.relkind FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname LIKE 'tokentracker\_%' ESCAPE '\'
      AND c.relkind IN ('r', 'v')
  LOOP
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated', obj.relname);
    IF obj.relkind = 'r' THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', obj.relname);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO project_admin', obj.relname);
    ELSE
      EXECUTE format('GRANT SELECT ON TABLE public.%I TO project_admin', obj.relname);
    END IF;
  END LOOP;
  FOR obj IN SELECT p.oid::regprocedure AS signature FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND (p.proname LIKE 'account\_%' ESCAPE '\'
      OR p.proname LIKE 'leaderboard\_%' ESCAPE '\'
      OR p.proname LIKE 'tokentracker\_%' ESCAPE '\'
      OR p.proname = 'refresh_tokentracker_device_identity')
  LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', obj.signature);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO project_admin', obj.signature);
    -- Upstream hourly_dedup_v2 has unqualified relations and no SET clause.
    -- Pin every function, including invoker functions, to trusted schemas.
    EXECUTE format('ALTER FUNCTION %s SET search_path TO pg_catalog, public, pg_temp', obj.signature);
  END LOOP;
END
$permissions$;

-- INFERRED_COMPATIBILITY_IMPLEMENTATION: daily interval arithmetic must use
-- UTC even if the database/session default observes DST. Otherwise a "day"
-- may be 23/25 hours and the replacement loop can delete an already-built day.
ALTER FUNCTION public.leaderboard_rollup_daily_replace_v2(timestamptz, timestamptz) SET timezone TO 'UTC';
ALTER FUNCTION public.leaderboard_rollup_daily_advance_v2() SET timezone TO 'UTC';

-- END SOURCE: backend/bootstrap/008_permissions.sql
