-- GENERATED by backend/community/build-migration.mjs. Do not edit.
-- Requires the reviewed TokenTracker MVP foundation. InsForge supplies one transaction.

-- BEGIN SOURCE: backend/community/sql/001_tables.sql SHA256=e1046950f49bb52c521ae59913a9c3ecd2607839fd59c1e24a73b35af33eb6ec
-- COMMUNITY_V1: new fork-owned objects; no changes to TokenTracker foundation.
-- Private invite-only communities. Quotas are trusted RPC parameters, not DDL.
DO $preflight$
BEGIN
  IF to_regclass('auth.users') IS NULL OR to_regclass('public.tokentracker_user_profiles') IS NULL
    OR to_regprocedure('public.leaderboard_usage_grouped(timestamp with time zone,timestamp with time zone)') IS NULL THEN
    RAISE EXCEPTION 'Community requires the verified MVP foundation';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='project_admin' AND rolbypassrls)
    OR NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='anon')
    OR NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    RAISE EXCEPTION 'Community requires the verified platform roles';
  END IF;
END $preflight$;
CREATE TABLE public.communities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 100),
  description text CHECK (char_length(description) <= 2000),
  owner_id uuid NOT NULL REFERENCES auth.users(id),
  invite_code text NOT NULL UNIQUE CHECK (invite_code ~ '^[A-F0-9]{32}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX communities_owner_idx ON public.communities(owner_id);
CREATE TABLE public.community_members (
  community_id uuid NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (community_id, user_id)
);
CREATE INDEX community_members_user_idx ON public.community_members(user_id, community_id);
-- Deferred to permit atomic creation of the community followed by its owner
-- membership. Also prevents owner removal by accidental server-side direct DML.
ALTER TABLE public.communities ADD CONSTRAINT communities_owner_member_fk
  FOREIGN KEY (id, owner_id) REFERENCES public.community_members(community_id, user_id)
  DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE public.community_transfer_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  community_id uuid NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  from_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  to_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','expired')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_user_id <> to_user_id),
  CHECK (expires_at > created_at)
);
CREATE UNIQUE INDEX community_transfer_one_pending_idx
  ON public.community_transfer_requests(community_id) WHERE status = 'pending';
CREATE INDEX community_transfer_recipient_idx ON public.community_transfer_requests(to_user_id, status, expires_at);
CREATE INDEX community_transfer_history_idx ON public.community_transfer_requests(community_id, created_at DESC, id);

-- END SOURCE: backend/community/sql/001_tables.sql

-- BEGIN SOURCE: backend/community/sql/002_membership_rpc.sql SHA256=7d3240eb515bc8d184871a90e7ac90f17fc889a8f3bf4624de5d5576296a8ae9
-- COMMUNITY_V1: SECURITY INVOKER, service-only. p_actor is a verified JWT subject
-- supplied by the future Edge; clients cannot execute any of these RPCs.
-- All writers lock user quota keys (sorted UUID), then community, then request.
-- READ COMMITTED required: counts after a waiting lock must see prior commits.
CREATE FUNCTION public.community_assert_actor(p_actor uuid) RETURNS void
LANGUAGE plpgsql STABLE SET search_path = pg_catalog, public, pg_temp AS $fn$
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (SELECT 1 FROM auth.users WHERE id = p_actor) THEN
    RAISE EXCEPTION 'INVALID_ACTOR' USING ERRCODE = '28000';
  END IF;
END $fn$;
CREATE FUNCTION public.community_validate_limits(p_limits jsonb) RETURNS void
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE k text;
BEGIN
  IF p_limits IS NULL OR jsonb_typeof(p_limits) <> 'object' THEN
    RAISE EXCEPTION 'INVALID_LIMITS' USING ERRCODE = '22023';
  END IF;
  FOREACH k IN ARRAY ARRAY['max_owned','max_joined','max_members'] LOOP
    IF jsonb_typeof(p_limits->k) IS DISTINCT FROM 'number' THEN
      RAISE EXCEPTION 'INVALID_LIMITS: %', k USING ERRCODE = '22023';
    END IF;
    IF (p_limits->>k) !~ '^[1-9][0-9]*$' OR (p_limits->>k)::numeric > 2147483647 THEN
      RAISE EXCEPTION 'INVALID_LIMITS: %', k USING ERRCODE = '22023';
    END IF;
  END LOOP;
  IF (SELECT count(*) FROM jsonb_object_keys(p_limits)) <> 3 THEN
    RAISE EXCEPTION 'INVALID_LIMITS: unexpected fields' USING ERRCODE = '22023';
  END IF;
END $fn$;
CREATE FUNCTION public.community_lock_users(p_users uuid[]) RETURNS void
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE u uuid;
BEGIN
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'COMMUNITY_WRITES_REQUIRE_READ_COMMITTED' USING ERRCODE = '25000';
  END IF;
  FOR u IN SELECT DISTINCT x FROM unnest(p_users) x WHERE x IS NOT NULL ORDER BY x LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended('community:user:' || u::text, 0));
  END LOOP;
END $fn$;
CREATE FUNCTION public.community_error(p_code text) RETURNS jsonb
LANGUAGE sql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $fn$
  SELECT jsonb_build_object('ok',false,'error',jsonb_build_object('code',p_code))
$fn$;
CREATE FUNCTION public.community_create(p_actor uuid, p_name text, p_description text, p_limits jsonb) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities; attempt integer; violated text;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_validate_limits(p_limits);
  IF p_name IS NULL OR char_length(btrim(p_name)) NOT BETWEEN 1 AND 100
     OR char_length(p_description) > 2000 THEN RETURN public.community_error('INVALID_INPUT'); END IF;
  PERFORM public.community_lock_users(ARRAY[p_actor]);
  IF (SELECT count(*) FROM public.communities WHERE owner_id=p_actor) >= (p_limits->>'max_owned')::integer
    THEN RETURN public.community_error('OWNED_LIMIT'); END IF;
  IF (SELECT count(*) FROM public.community_members WHERE user_id=p_actor) >= (p_limits->>'max_joined')::integer
    THEN RETURN public.community_error('JOINED_LIMIT'); END IF;
  -- Collision retries only for the invite-code unique constraint, never hide
  -- unrelated constraint errors. Each iteration's subtransaction is atomic.
  FOR attempt IN 1..5 LOOP
    BEGIN
      INSERT INTO public.communities(name,description,owner_id,invite_code)
      VALUES (btrim(p_name),p_description,p_actor,upper(replace(gen_random_uuid()::text,'-',''))) RETURNING * INTO c;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      GET STACKED DIAGNOSTICS violated = CONSTRAINT_NAME;
      IF violated <> 'communities_invite_code_key' THEN RAISE; END IF;
      IF attempt=5 THEN RAISE; END IF;
    END;
  END LOOP;
  INSERT INTO public.community_members(community_id,user_id) VALUES(c.id,p_actor);
  RETURN jsonb_build_object('ok',true,'community',to_jsonb(c));
END $fn$;
CREATE FUNCTION public.community_join(p_actor uuid, p_invite_code text, p_limits jsonb) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_validate_limits(p_limits);
  PERFORM public.community_lock_users(ARRAY[p_actor]);
  SELECT * INTO c FROM public.communities WHERE invite_code=upper(btrim(p_invite_code)) FOR UPDATE;
  IF NOT FOUND THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  IF EXISTS (SELECT 1 FROM public.community_members WHERE community_id=c.id AND user_id=p_actor) THEN
    RETURN jsonb_build_object('ok',true,'already_member',true,'community_id',c.id);
  END IF;
  IF (SELECT count(*) FROM public.community_members WHERE user_id=p_actor) >= (p_limits->>'max_joined')::integer
    THEN RETURN public.community_error('JOINED_LIMIT'); END IF;
  IF (SELECT count(*) FROM public.community_members WHERE community_id=c.id) >= (p_limits->>'max_members')::integer
    THEN RETURN public.community_error('MEMBER_LIMIT'); END IF;
  INSERT INTO public.community_members(community_id,user_id) VALUES(c.id,p_actor);
  RETURN jsonb_build_object('ok',true,'already_member',false,'community_id',c.id);
END $fn$;
CREATE FUNCTION public.community_leave(p_actor uuid, p_community_id uuid) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_lock_users(ARRAY[p_actor]);
  SELECT * INTO c FROM public.communities WHERE id=p_community_id FOR UPDATE;
  IF NOT FOUND OR NOT EXISTS(SELECT 1 FROM public.community_members WHERE community_id=c.id AND user_id=p_actor)
    THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  IF c.owner_id=p_actor THEN RETURN public.community_error('OWNER_CANNOT_LEAVE'); END IF;
  UPDATE public.community_transfer_requests SET status='expired'
    WHERE community_id=c.id AND to_user_id=p_actor AND status='pending';
  DELETE FROM public.community_members WHERE community_id=c.id AND user_id=p_actor;
  RETURN jsonb_build_object('ok',true,'community_id',c.id);
END $fn$;
CREATE FUNCTION public.community_delete(p_actor uuid, p_community_id uuid, p_confirmation_name text) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_lock_users(ARRAY[p_actor]);
  SELECT * INTO c FROM public.communities WHERE id=p_community_id FOR UPDATE;
  IF NOT FOUND OR c.owner_id<>p_actor THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  IF p_confirmation_name IS DISTINCT FROM c.name THEN RETURN public.community_error('CONFIRMATION_REQUIRED'); END IF;
  DELETE FROM public.communities WHERE id=c.id;
  RETURN jsonb_build_object('ok',true,'community_id',c.id);
END $fn$;

-- END SOURCE: backend/community/sql/002_membership_rpc.sql

-- BEGIN SOURCE: backend/community/sql/003_transfer_rpc.sql SHA256=4fc160878fac4318a7851c155952b8f1694bad890957a4fff80967f548e42c1b
-- COMMUNITY_V1: expiration is enforced on every action. No scheduler required.
-- Expected failures return JSON, allowing an expired status update to commit;
-- raising an exception after that update would incorrectly roll it back.
CREATE FUNCTION public.community_create_transfer(p_actor uuid, p_community_id uuid, p_to_user_id uuid) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp SET timezone = 'UTC' AS $fn$
DECLARE c public.communities; r public.community_transfer_requests; t timestamptz;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  IF p_to_user_id IS NULL OR p_to_user_id=p_actor THEN RETURN public.community_error('INVALID_TARGET'); END IF;
  PERFORM public.community_lock_users(ARRAY[p_actor,p_to_user_id]);
  SELECT * INTO c FROM public.communities WHERE id=p_community_id FOR UPDATE;
  IF NOT FOUND OR c.owner_id<>p_actor THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  IF NOT EXISTS (SELECT 1 FROM public.community_members WHERE community_id=c.id AND user_id=p_to_user_id)
    THEN RETURN public.community_error('TARGET_NOT_MEMBER'); END IF;
  t := clock_timestamp();
  UPDATE public.community_transfer_requests SET status='expired'
    WHERE community_id=c.id AND status='pending' AND expires_at<=t;
  IF EXISTS(SELECT 1 FROM public.community_transfer_requests WHERE community_id=c.id AND status='pending')
    THEN RETURN public.community_error('TRANSFER_PENDING'); END IF;
  INSERT INTO public.community_transfer_requests(community_id,from_user_id,to_user_id,created_at,expires_at)
    VALUES(c.id,p_actor,p_to_user_id,t,t+interval '7 days') RETURNING * INTO r;
  RETURN jsonb_build_object('ok',true,'transfer',to_jsonb(r));
END $fn$;
CREATE FUNCTION public.community_accept_transfer(p_actor uuid, p_request_id uuid, p_limits jsonb) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities; r public.community_transfer_requests;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_validate_limits(p_limits);
  SELECT * INTO r FROM public.community_transfer_requests WHERE id=p_request_id;
  IF NOT FOUND OR r.to_user_id<>p_actor THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  PERFORM public.community_lock_users(ARRAY[r.from_user_id,p_actor]);
  SELECT * INTO c FROM public.communities WHERE id=r.community_id FOR UPDATE;
  IF NOT FOUND THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  SELECT * INTO r FROM public.community_transfer_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR r.to_user_id<>p_actor THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  IF r.status='accepted' THEN RETURN jsonb_build_object('ok',true,'already_accepted',true,'transfer',to_jsonb(r),'owner_id',c.owner_id); END IF;
  IF r.status<>'pending' THEN RETURN public.community_error('TRANSFER_NOT_PENDING'); END IF;
  IF r.expires_at<=clock_timestamp() OR c.owner_id<>r.from_user_id
     OR NOT EXISTS(SELECT 1 FROM public.community_members WHERE community_id=c.id AND user_id=p_actor) THEN
    UPDATE public.community_transfer_requests SET status='expired' WHERE id=r.id;
    RETURN public.community_error('TRANSFER_EXPIRED');
  END IF;
  IF (SELECT count(*) FROM public.communities WHERE owner_id=p_actor) >= (p_limits->>'max_owned')::integer
    THEN RETURN public.community_error('OWNED_LIMIT'); END IF;
  UPDATE public.communities SET owner_id=p_actor WHERE id=c.id;
  UPDATE public.community_transfer_requests SET status='accepted' WHERE id=r.id RETURNING * INTO r;
  RETURN jsonb_build_object('ok',true,'already_accepted',false,'transfer',to_jsonb(r),'owner_id',p_actor);
END $fn$;
CREATE FUNCTION public.community_reject_transfer(p_actor uuid, p_request_id uuid) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SET search_path = pg_catalog, public, pg_temp AS $fn$
DECLARE c public.communities; r public.community_transfer_requests;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  SELECT * INTO r FROM public.community_transfer_requests WHERE id=p_request_id;
  IF NOT FOUND OR r.to_user_id<>p_actor THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  PERFORM public.community_lock_users(ARRAY[r.from_user_id,p_actor]);
  SELECT * INTO c FROM public.communities WHERE id=r.community_id FOR UPDATE;
  IF NOT FOUND THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  SELECT * INTO r FROM public.community_transfer_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR r.to_user_id<>p_actor THEN RETURN public.community_error('TRANSFER_UNAVAILABLE'); END IF;
  IF r.status='rejected' THEN RETURN jsonb_build_object('ok',true,'already_rejected',true,'transfer',to_jsonb(r)); END IF;
  IF r.status<>'pending' THEN RETURN public.community_error('TRANSFER_NOT_PENDING'); END IF;
  IF r.expires_at<=clock_timestamp() OR c.owner_id<>r.from_user_id
     OR NOT EXISTS(SELECT 1 FROM public.community_members WHERE community_id=c.id AND user_id=p_actor) THEN
    UPDATE public.community_transfer_requests SET status='expired' WHERE id=r.id;
    RETURN public.community_error('TRANSFER_EXPIRED');
  END IF;
  UPDATE public.community_transfer_requests SET status='rejected' WHERE id=r.id RETURNING * INTO r;
  RETURN jsonb_build_object('ok',true,'already_rejected',false,'transfer',to_jsonb(r));
END $fn$;

-- END SOURCE: backend/community/sql/003_transfer_rpc.sql

-- BEGIN SOURCE: backend/community/sql/004_read_rpc.sql SHA256=46746fbf4002b030a1bc07c6221200692ae31fc71e723eb0acc4a45a06ebfa7b
-- COMMUNITY_V1: STABLE read functions share the caller's statement snapshot.
-- Membership authorization, usage filtering, zero-fill and ranking stay in DB.
CREATE FUNCTION public.community_read(p_actor uuid, p_limits jsonb,
  p_community_id uuid DEFAULT NULL, p_limit integer DEFAULT 50, p_offset integer DEFAULT 0) RETURNS jsonb
LANGUAGE plpgsql STABLE SET search_path = pg_catalog, public, pg_temp SET timezone = 'UTC' AS $fn$
DECLARE c public.communities; rows jsonb; requests jsonb; owned bigint; joined bigint;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  PERFORM public.community_validate_limits(p_limits);
  IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100 OR p_offset IS NULL OR p_offset<0
    THEN RETURN public.community_error('INVALID_PAGINATION'); END IF;
  SELECT count(*) INTO owned FROM public.communities WHERE owner_id=p_actor;
  SELECT count(*) INTO joined FROM public.community_members WHERE user_id=p_actor;
  IF p_community_id IS NULL THEN
    SELECT coalesce(jsonb_agg(item ORDER BY created_at DESC,id),'[]'::jsonb) INTO rows FROM (
      SELECT co.id,co.created_at,
        (CASE WHEN co.owner_id=p_actor THEN to_jsonb(co) ELSE to_jsonb(co)-'invite_code' END)
        || jsonb_build_object('is_owner',co.owner_id=p_actor,'joined_at',m.joined_at,
          'member_count',(SELECT count(*) FROM public.community_members cm WHERE cm.community_id=co.id)) AS item
      FROM public.communities co JOIN public.community_members m ON m.community_id=co.id AND m.user_id=p_actor
      ORDER BY co.created_at DESC,co.id LIMIT p_limit OFFSET p_offset
    ) page;
    SELECT coalesce(jsonb_agg(to_jsonb(r) || jsonb_build_object('status',
      CASE WHEN r.expires_at<=statement_timestamp() THEN 'expired' ELSE r.status END)
      ORDER BY r.created_at,r.id),'[]'::jsonb) INTO requests
      FROM public.community_transfer_requests r
      WHERE r.to_user_id=p_actor AND r.status='pending'
        AND EXISTS(SELECT 1 FROM public.community_members m WHERE m.community_id=r.community_id AND m.user_id=p_actor);
    RETURN jsonb_build_object('ok',true,'communities',rows,'incoming_transfers',requests,
      'owned_count',owned,'joined_count',joined,'limits',p_limits,'limit',p_limit,'offset',p_offset);
  END IF;
  SELECT * INTO c FROM public.communities WHERE id=p_community_id
    AND EXISTS(SELECT 1 FROM public.community_members WHERE community_id=p_community_id AND user_id=p_actor);
  IF NOT FOUND THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  SELECT coalesce(jsonb_agg(item ORDER BY joined_at,user_id),'[]'::jsonb) INTO rows FROM (
    SELECT m.user_id,m.joined_at,jsonb_build_object('user_id',m.user_id,'joined_at',m.joined_at,
      'display_name',coalesce(nullif(s.display_name,''),nullif(u.profile->>'name',''),'Member'),
      'avatar_url',p.avatar_url,'is_owner',m.user_id=c.owner_id) AS item
    FROM public.community_members m JOIN auth.users u ON u.id=m.user_id
    LEFT JOIN public.tokentracker_user_settings s ON s.user_id=m.user_id
    LEFT JOIN public.tokentracker_user_profiles p ON p.user_id=m.user_id
    WHERE m.community_id=c.id ORDER BY m.joined_at,m.user_id LIMIT p_limit OFFSET p_offset
  ) page;
  SELECT coalesce(jsonb_agg(to_jsonb(r) || jsonb_build_object('status',
    CASE WHEN r.expires_at<=statement_timestamp() THEN 'expired' ELSE r.status END)
    ORDER BY r.created_at,r.id),'[]'::jsonb) INTO requests
    FROM public.community_transfer_requests r WHERE r.community_id=c.id AND r.status='pending'
      AND (c.owner_id=p_actor OR r.to_user_id=p_actor);
  RETURN jsonb_build_object('ok',true,'community',CASE WHEN c.owner_id=p_actor THEN to_jsonb(c) ELSE to_jsonb(c)-'invite_code' END,
    'is_owner',c.owner_id=p_actor,'members',rows,'transfers',requests,
    'member_count',(SELECT count(*) FROM public.community_members WHERE community_id=c.id),
    'limits',p_limits,'owned_count',owned,'joined_count',joined,'limit',p_limit,'offset',p_offset);
END $fn$;
CREATE FUNCTION public.community_leaderboard(p_actor uuid, p_community_id uuid, p_period text,
  p_limit integer DEFAULT 50, p_offset integer DEFAULT 0,
  p_excluded_user_ids uuid[] DEFAULT ARRAY[]::uuid[], p_as_of timestamptz DEFAULT now()) RETURNS jsonb
LANGUAGE plpgsql STABLE SET search_path = pg_catalog, public, pg_temp SET timezone = 'UTC' AS $fn$
DECLARE start_at timestamptz; end_at timestamptz; result jsonb;
BEGIN
  PERFORM public.community_assert_actor(p_actor);
  IF NOT EXISTS(SELECT 1 FROM public.community_members WHERE community_id=p_community_id AND user_id=p_actor)
    THEN RETURN public.community_error('COMMUNITY_UNAVAILABLE'); END IF;
  IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100 OR p_offset IS NULL OR p_offset<0
    THEN RETURN public.community_error('INVALID_PAGINATION'); END IF;
  IF p_period IS NULL OR p_period NOT IN ('week','month','total') OR p_as_of IS NULL OR NOT isfinite(p_as_of)
    OR p_as_of < timestamptz '1970-01-01 00:00:00+00' THEN RETURN public.community_error('INVALID_PERIOD'); END IF;
  -- Same Monday-start UTC calendar ranges as the MVP global refresh. Exclusive
  -- upper boundary includes the final calendar day. total starts at epoch.
  IF p_period='week' THEN start_at:=date_trunc('week',p_as_of); end_at:=start_at+interval '7 days';
  ELSIF p_period='month' THEN start_at:=date_trunc('month',p_as_of); end_at:=start_at+interval '1 month';
  ELSE start_at:=timestamptz '1970-01-01 00:00:00+00'; end_at:=date_trunc('day',p_as_of)+interval '1 day'; END IF;
  -- Existing aggregation is not member-parameterized. It may aggregate the
  -- whole site before this filter; no copied token table or ranking snapshots.
  WITH members AS MATERIALIZED (
    SELECT user_id FROM public.community_members WHERE community_id=p_community_id
  ), eligible AS MATERIALIZED (
    SELECT user_id FROM members m WHERE NOT EXISTS (
      SELECT 1 FROM unnest(p_excluded_user_ids) blocked(user_id) WHERE blocked.user_id=m.user_id)
  ), usage AS MATERIALIZED (
    SELECT a.user_id,sum(a.total_tokens)::numeric AS tokens
    FROM jsonb_to_recordset(public.leaderboard_usage_grouped(start_at,end_at)) AS a(user_id uuid,total_tokens bigint)
    JOIN eligible e ON e.user_id=a.user_id GROUP BY a.user_id
  ), ranked AS MATERIALIZED (
    SELECT e.user_id,coalesce(u.tokens,0) AS tokens,
      dense_rank() OVER(ORDER BY coalesce(u.tokens,0) DESC) AS rank
    FROM eligible e LEFT JOIN usage u ON u.user_id=e.user_id
  ), formatted AS MATERIALIZED (
    SELECT r.user_id,r.tokens,r.rank,jsonb_build_object('user_id',r.user_id,
      'total_tokens',r.tokens::text,'rank',r.rank,
      'display_name',coalesce(nullif(s.display_name,''),nullif(u.profile->>'name',''),'Member'),
      'avatar_url',p.avatar_url) AS item
    FROM ranked r JOIN auth.users u ON u.id=r.user_id
    LEFT JOIN public.tokentracker_user_settings s ON s.user_id=r.user_id
    LEFT JOIN public.tokentracker_user_profiles p ON p.user_id=r.user_id
  ), page AS (
    SELECT * FROM formatted ORDER BY tokens DESC,user_id LIMIT p_limit OFFSET p_offset
  ) SELECT jsonb_build_object('ok',true,'community_id',p_community_id,'period',p_period,
    'from_day',start_at::date,'to_day',(end_at-interval '1 day')::date,
    'from',start_at,'to_exclusive',end_at,'basis','client_reported_tokens',
    'automatic_anticheat',false,'member_count',(SELECT count(*) FROM members),
    'ranked_count',(SELECT count(*) FROM ranked),
    'excluded_member_count',(SELECT count(*) FROM members)-(SELECT count(*) FROM ranked),
    'rows',coalesce((SELECT jsonb_agg(item ORDER BY tokens DESC,user_id) FROM page),'[]'::jsonb),
    'me',(SELECT item FROM formatted WHERE user_id=p_actor),'limit',p_limit,'offset',p_offset)
    INTO result;
  RETURN result;
END $fn$;

-- END SOURCE: backend/community/sql/004_read_rpc.sql

-- BEGIN SOURCE: backend/community/sql/005_permissions.sql SHA256=c4477f89ade1c1598106b8d6b5acdacdcc9ae3fd64d24c95771554787e2e4908
-- COMMUNITY_V1: project_admin BYPASSRLS was verified by own-project preflight.
-- No browser table access, no client RPC execution, no SECURITY DEFINER bypass.
DO $permissions$
DECLARE obj record; name text;
BEGIN
  FOREACH name IN ARRAY ARRAY['communities','community_members','community_transfer_requests'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated',name);
    EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.%I TO project_admin',name);
  END LOOP;
  FOR obj IN SELECT p.oid::regprocedure AS signature FROM pg_proc p
    WHERE p.pronamespace='public'::regnamespace AND p.proname IN (
      'community_assert_actor','community_validate_limits','community_lock_users','community_error',
      'community_create','community_join','community_leave','community_create_transfer',
      'community_accept_transfer','community_reject_transfer','community_delete','community_read','community_leaderboard')
  LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',obj.signature);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO project_admin',obj.signature);
  END LOOP;
END $permissions$;

-- END SOURCE: backend/community/sql/005_permissions.sql
