// Generates self-contained ESM entry files. Local files/secrets are never read
// except the explicitly enumerated reviewed code sources below.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { specs,sdkImport } from './edge-spec.mjs';
const require=createRequire(new URL('../bootstrap/package.json',import.meta.url));
const ts=require('typescript');
export const dir=path.dirname(fileURLToPath(import.meta.url)), root=path.resolve(dir,'../..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8').replace(/\r\n/g,'\n');
const hash=text=>createHash('sha256').update(text).digest('hex');
const shared=['backend/community/config.mjs','backend/edge/server-credential.ts','backend/community/src/runtime.ts'];
export function buildEdges() {
  const sources=[...shared,'backend/community/edge-spec.mjs','backend/community/build-edges.mjs',...specs.map(s=>`backend/community/src/${s.name}.ts`)];
  const sharedText=shared.map(name=>read(name).replace(/^import .*;\n/gm,'').replace(/^export (?=function)/gm,'' )).join('\n');
  const entries=specs.map(spec=>{
    const source=`backend/community/src/${spec.name}.ts`,entry=`backend/community/edge/${spec.name}.js`;
    assert.equal(read(source),`import { makeCommunityHandler } from "./runtime.ts";\nexport default makeCommunityHandler("${spec.operation}");\n`);
    const combined=`import { createAdminClient } from "${sdkImport}";\n${sharedText}\n${read(source).replace(/^import .*;\n/gm,'')}`;
    const compiled=ts.transpileModule(combined,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext},reportDiagnostics:true});
    assert.equal(compiled.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error).length,0);
    const body='// GENERATED by backend/community/build-edges.mjs; do not edit.\n'+compiled.outputText;
    return {...spec,source,entry,sourceSha256:hash(read(source)),entrySha256:hash(body),body};
  });
  return {entries,manifest:{sdkImport,sources:sources.map(source=>({source,sha256:hash(read(source))})),
    functions:entries.map(({body,...entry})=>entry)}};
}
export function checkEdges() {
  const expected=buildEdges(),actual=JSON.parse(read('backend/community/manifest.json'));
  assert.deepEqual(actual,expected.manifest,'Community source/manifest drift');
  assert.deepEqual(fs.readdirSync(path.join(dir,'edge')).filter(n=>n.endsWith('.js')).sort(),specs.map(s=>`${s.name}.js`).sort());
  for(const row of expected.entries) assert.equal(read(row.entry),row.body,`Publish entry drift: ${row.name}`);
  return expected.entries;
}
if(process.argv[1] && import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href) {
  if(process.argv.includes('--check')) {checkEdges();console.log('PASS 9 Community entries and all shared source hashes match');}
  else {
    const built=buildEdges();fs.mkdirSync(path.join(dir,'edge'),{recursive:true});
    for(const row of built.entries) fs.writeFileSync(path.join(root,row.entry),row.body);
    fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(built.manifest,null,2)+'\n');
    console.log('Generated 9 Community single-file entries; nothing deployed');
  }
}
